
## Figure 6A

```{r,echo=T}
metadata_meta <- read.csv('input//metadata_meta_107.csv',header=T,row.names = 1)
metadata_meta <- subset(metadata_meta,metadata_meta$national=='tibetan')
species <- read.table('input//kraken2_combined_unstratified_species.txt',header = T,sep = '\t',quote = "")
tax <- read.table('input//kraken2_taxonomy.txt',header = T,sep = '\t',quote = "")

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species <- merge(species.tax,species,by='species')
Bacteria <- subset(species,kingdom=='k__Bacteria')
rownames(Bacteria) <- Bacteria$species
Bacteria<- Bacteria[,c(8:114)]

Bacteria <- as.data.frame(t(Bacteria))
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100
Bacteria.ra$seq_ID <- rownames(Bacteria.ra)
Bacteria.ra <- merge(metadata_meta,Bacteria.ra,by='seq_ID')
rownames(Bacteria.ra) <- Bacteria.ra$seq_ID
Bacteria.ra <- Bacteria.ra[,-c(1:8)]
Bacteria.ra <- na.omit(Bacteria.ra)
Bacteria.ra <- Bacteria.ra[Bacteria.ra$Prevotella_copri<20,]
bray <- as.matrix(vegdist(Bacteria.ra,"bray"))
rownames(metadata_meta) <- metadata_meta$seq_ID
metadata_meta <- metadata_meta[rownames(bray),]
bray <- bray[rownames(metadata_meta), rownames(metadata_meta)] 


tibetan.met <- subset(metadata_meta,national=='tibetan')
tibetan.bray <- bray[rownames(tibetan.met), rownames(tibetan.met)] 

 adonis(tibetan.bray~tibetan.met$relocation.years)$aov.tab







group_1M_1Y= subset(metadata_meta, relocation.years %in% c("1M","1Y"))
sub_dis1 = bray[rownames(group_1M_1Y),rownames(group_1M_1Y)]
adon.result1<-adonis(sub_dis1 ~ group_1M_1Y$group)$aov.tab


group_1M_2Y= subset(metadata_meta, relocation.years %in% c("1M","2Y"))
sub_dis2 = bray[rownames(group_1M_2Y),rownames(group_1M_2Y)]
adon.result2<-adonis(sub_dis2 ~ group_1M_2Y$group)$aov.tab


group_1Y_2Y = subset(metadata_meta,  relocation.years %in% c("1Y","2Y"))
sub_dis3 = bray[rownames(group_1Y_2Y),rownames(group_1Y_2Y)]
adon.result3<-adonis(sub_dis3 ~ group_1Y_2Y$group)$aov.tab



#PCOA 计算
bray.pcoa <-  cmdscale(bray, k=2, eig=T) # k is dimension,  eig is eigenvalues
bray.points <-  as.data.frame(bray.pcoa$points) # get coordinate string, format to dataframme
colnames(bray.points) = c("x", "y") 
bray.eig <- bray.pcoa$eig
#添加样品组信息：合并PCoA坐标与实验设计
bray.points <-  cbind(bray.points,tibetan.met[match(rownames(bray.points), rownames(tibetan.met)), ])


bray.points <- na.omit(bray.points)

bray.points$relocation.years <- car::recode(bray.points$relocation.years,' "1M"="Baseline";"1Y"="Y1";"2Y"="Y2" ')





ggscatter(bray.points,x="x",y="y",
              color="relocation.years",
              fill="relocation.years",
              palette=ggsci::pal_npg( alpha = 1)(3) ,
              shape=21,
              size=2,
              ellipse=T,
              ellipse.level=0.5,
              linetype = "solid",
              title="LPC (P=0.002)",
              legend="right",
  xlab =paste("PCoA 1 (", format(100 * bray.eig[1] / sum(bray.eig), digits=4), "%)", sep=""),
  ylab=paste("PCoA 2 (", format(100 * bray.eig[2] / sum(bray.eig), digits=4), "%)", sep=""),
    ggtheme=theme_cleveland()+  
    theme(plot.title = element_text(hjust = 0.5,size=15))+
    theme(axis.title.x =element_text(size=14,color = 'black'),
          axis.title.y=element_text(size=14,color = 'black'),#设置x.y标题上文本的名称
          axis.text.x = element_text(size=14,color = 'black'),
          axis.text.y = element_text(size=14,color = 'black'),
          legend.title = element_blank(),
          legend.text = element_text(size=14,color = 'black')))



```

# Figure 6B

```{r global_options, iNegativelude=FALSE}
mypal1 <- ggsci::pal_lancet( alpha = 1)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.5)(9)

library(vegan)
library(ggpubr)
library(ggplot2)
library(reshape2)




metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)
species <- read.table('input/kraken2_combined_unstratified_species.txt',header = T,sep = '\t',quote = "")
tax <- read.table('input/kraken2_taxonomy.txt',header = T,sep = '\t',quote = "")

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species <- merge(species.tax,species,by='species')
Bacteria <- subset(species,kingdom=='k__Bacteria')
rownames(Bacteria) <- Bacteria$species
Bacteria<- Bacteria[,c(8:114)]

Bacteria <- as.data.frame(t(Bacteria))
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100
Bacteria.ra$seq_ID <- rownames(Bacteria.ra)
Bacteria.ra <- merge(metadata_meta,Bacteria.ra,by='seq_ID')
rownames(Bacteria.ra) <- Bacteria.ra$seq_ID
Bacteria.ra <- Bacteria.ra[,-c(1:8)]
Bacteria.ra <- na.omit(Bacteria.ra)
Bacteria.ra <- Bacteria.ra[Bacteria.ra$Prevotella_copri>20,]
bray <- as.matrix(vegdist(Bacteria.ra,"bray"))
rownames(metadata_meta) <- metadata_meta$seq_ID
metadata_meta <- metadata_meta[rownames(bray),]
bray <- bray[rownames(metadata_meta), rownames(metadata_meta)] 


tibetan.met <- subset(metadata_meta,national=='tibetan')
tibetan.bray <- bray[rownames(tibetan.met), rownames(tibetan.met)] 


tibetan.adonis <-  adonis(tibetan.bray~tibetan.met$relocation.years)$aov.tab







group_1M_1Y= subset(metadata_meta, relocation.years %in% c("1M","1Y"))
sub_dis1 = bray[rownames(group_1M_1Y),rownames(group_1M_1Y)]
adon.result1<-adonis(sub_dis1 ~ group_1M_1Y$group)$aov.tab


group_1M_2Y= subset(metadata_meta, relocation.years %in% c("1M","2Y"))
sub_dis2 = bray[rownames(group_1M_2Y),rownames(group_1M_2Y)]
adon.result2<-adonis(sub_dis2 ~ group_1M_2Y$group)$aov.tab


group_1Y_2Y = subset(metadata_meta,  relocation.years %in% c("1Y","2Y"))
sub_dis3 = bray[rownames(group_1Y_2Y),rownames(group_1Y_2Y)]
adon.result3<-adonis(sub_dis3 ~ group_1Y_2Y$group)$aov.tab



#PCOA 计算
bray.pcoa <-  cmdscale(bray, k=2, eig=T) # k is dimension,  eig is eigenvalues
bray.points <-  as.data.frame(bray.pcoa$points) # get coordinate string, format to dataframme
colnames(bray.points) = c("x", "y") 
bray.eig <- bray.pcoa$eig
#添加样品组信息：合并PCoA坐标与实验设计
bray.points <-  cbind(bray.points,tibetan.met[match(rownames(bray.points), rownames(tibetan.met)), ])


bray.points <- na.omit(bray.points)


bray.points$relocation.years <- car::recode(bray.points$relocation.years,' "1M"="Baseline";"1Y"="Y1";"2Y"="Y2" ')





ggscatter(bray.points,x="x",y="y",
              color="relocation.years",
              fill="relocation.years",
              palette=ggsci::pal_npg( alpha = 1)(3) ,
              shape=21,
              size=2,
              ellipse=T,
              ellipse.level=0.5,
              linetype = "solid",
              title="HPC (P=0.11)",
              legend="right",
  xlab =paste("PCoA 1 (", format(100 * bray.eig[1] / sum(bray.eig), digits=4), "%)", sep=""),
  ylab=paste("PCoA 2 (", format(100 * bray.eig[2] / sum(bray.eig), digits=4), "%)", sep=""),
    ggtheme=theme_cleveland()+  
    theme(plot.title = element_text(hjust = 0.5,size=15))+
    theme(axis.title.x =element_text(size=14,color = 'black'),
          axis.title.y=element_text(size=14,color = 'black'),#设置x.y标题上文本的名称
          axis.text.x = element_text(size=14,color = 'black'),
          axis.text.y = element_text(size=14,color = 'black'),
          legend.title = element_blank(),
          legend.text = element_text(size=14,color = 'black')))


```

# Figure 6C

```{r,echo=T}

species <- read.table('input/metaphlan2_merged_species.txt',header = T,sep='\t')
tax <- read.table('input/tax.txt',header = T,sep='\t')

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species.tax <- species.tax[!duplicated(species.tax$species), ] # 去重复
species <- merge(species.tax,species,by='species')

Bacteria <- subset(species,kingdom=='Bacteria')
rownames(Bacteria) <- Bacteria$species

Bacteria.ra <- Bacteria[,c(8:114)]
Bacteria.ra <- as.data.frame(t(Bacteria.ra))


metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)



Bacteria.ra$seq_ID <- rownames(Bacteria.ra)


Bacteria.ra <- merge(metadata_meta,Bacteria.ra,by='seq_ID')


Bacteria.ra <- subset(Bacteria.ra,national=='tibetan')

Bacteria.ra$PC <- car::recode(Bacteria.ra$Prevotella_copri," 0:20='LPC';else='HPC'")

mean(Bacteria.ra$Prevotella_copri)

ggplot(Bacteria.ra, aes(Bacteria.ra$Prevotella_copri)) +
    geom_histogram(aes(y=..density..))+
  geom_density(alpha = 1,aes(fill=PC))


ggplot(Bacteria.ra, aes(Bacteria.ra$Prevotella_copri)) +
  geom_density(alpha = 1,color='red',size=1)+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,face='italic',colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  xlab('P. copri Abundance(%)')+
  ylab('Density')+
  geom_vline(aes(xintercept=20.1),size=1)+
  annotate(geom = "text", x = 21, y = 0.016, 
    label = 'mean=20.1', hjust = 0, vjust = 1, size = 4)





ggplot(data=Bacteria.ra,aes(x=log2(Prevotella_copri)))+
  geom_histogram(color='black',fill="#E64B35E5",alpha=0.5,
                 aes(y=..density..))+
  geom_density(alpha = 1,color='black',size=1)+
   theme_classic() + 
  ggtitle('Distribution of P. copri')+
  
  labs( y = 'Density',x='log2 (Abundance %)') +
  theme(
        axis.text.x=element_text(colour = 'black',size=14),
        axis.title.x=element_text(colour = 'black',size=14),
        axis.text.y=element_text(colour = 'black',size=14),
        axis.title.y =element_text(colour = 'black',size=14),
        strip.background = element_blank(),
        strip.text = element_text(colour = 'black',size=14)) + 
  theme(legend.position = "right",
        legend.text =element_text(colour = 'black',size=14),
        legend.title =element_blank() ) + 
  theme(panel.grid=element_blank()) +    ## 去掉白色圆框和中间的坐标线
  theme(panel.border=element_blank())




stratified.pathway <- read.csv('input/humann2_pathabundance_cpm_stratified.tsv',header=T,sep ="\t")

stratified.pathway <- stratified.pathway[-which(stratified.pathway$pathway_ID%in%'UNINTEGRATED'),]





p.copri.pathway <- subset(stratified.pathway,species=='s__Prevotella_copri')
rownames(p.copri.pathway) <- p.copri.pathway$pathway
p.copri.pathway <-p.copri.pathway[,-c(1:5)]
p.copri.pathway <- as.data.frame(t(p.copri.pathway))

p.copri.pathway$seq_ID <- row.names(p.copri.pathway)

p.copri.pathway <- merge(Bacteria.ra[,c(1:8,333)],p.copri.pathway,by='seq_ID')


p.copri.pathway.long <- melt(p.copri.pathway)






ggboxplot(p.copri.pathway.long, x="variable", y="value", 
          fill = "PC",
          outlier.colour='white')+
  stat_compare_means(aes(group=national), label = "p.signif",method = 'wilcox')+
  scale_fill_manual(values = c('#fa0b10','#2c60fd','#fa0b10','#fa0b10'))+  #设置填充的颜色
  scale_color_manual(values=c('#fa0b10','#2c60fd','#fa0b10','#fa0b10'))+ #设置散点图的圆圈的颜色为黑色
  ggtitle("pathway related to P.copri")+ #设置总的标题
  theme_classic()+ #背景变为白色
  theme(legend.position="right", #不需要图例
        axis.text.x=element_text(colour="black",size=12), #设置x轴刻度标签的字体属性
        axis.text.y=element_text(colour="black",size=12,
                                 face = 'italic'), #设置x轴刻度标签的字体属性
        axis.title.y=element_text(size = 12,), #设置y轴的标题的字体属性
        axis.title.x=element_text(size = 12,), #设置x轴的标题的字体属性
        plot.title = element_text(size=12,face="bold",hjust = 0.5), #设置总标题的字体属性
        panel.grid.major = element_blank(), #不显示网格线
        panel.grid.minor = element_blank())+
  coord_flip()+
  ylab("Copies per million")+xlab("")#设置x轴和y轴的标题





ggplot(p.copri.pathway.long,aes(x=PC,y=value,fill=PC))+ #”fill=“设置填充颜色
    facet_wrap(~variable)+
    stat_boxplot(geom = "errorbar",width=0.25,size=0.25,aes(color="black"))+ #由于自带的箱形图没有胡须末端没有短横线，使用误差条的方式补上
    geom_boxplot(size=0.25,width=0.4,outlier.fill="white",outlier.color="white")+ #size设置箱线图的边框线和胡须的线宽度，fill设置填充颜色，outlier.fill和outlier.color设置异常点的属性
    geom_jitter(width=0.15,color="black",shape = 20,size=1)+ #设置为向水平方向抖动的散点图，width指定了向水平方向抖动，不改变纵轴的值
   scale_fill_manual(values=c('#b200f8','#04f60b','pink','red'))+
    scale_color_manual(values="black")+ #设置散点图的圆圈的颜色为黑色
    theme_cleveland()+ #背景变为白色
  ggtitle('P_copri')+
    theme(legend.position="none", #不需要图例
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="italic",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("Copies per million")+xlab("")+  #设置x轴和y轴的标题
    stat_compare_means(label = "p.signif",comparisons=list(c("LPC", "HPC")))






pathway <- read.table('input/humann2_pathabundance_cpm_unstratified.tsv',header = T,sep='\t',row.names = 1)
pathway <- as.data.frame(t(pathway))

pathway$seq_ID <- rownames(pathway)
pathway <- merge(Bacteria.ra[,c(1:8,333)],pathway,by='seq_ID')

#write.table(pathway,'pathway_lefse/pathway_PC.txt',sep='\t')



Pathway.lefse <- read.table('pathway_lefse/pathway_PC.lefse_internal_res',header = T,sep='\t')

tax <- read.csv('input/pathway.tax.csv',header = T)
Pathway.lefse <- merge(tax,Pathway.lefse,by='pathway_ID')

Pathway.lefse_3 <- subset(Pathway.lefse,LDA.1>3.2)
Pathway.lefse_3 <- Pathway.lefse_3[order(Pathway.lefse_3$LDA,decreasing = F),]
rownames(Pathway.lefse_3) <- Pathway.lefse_3$pathway

ggplot(data = Pathway.lefse_3 , mapping = aes(x = reorder(pathway,-LDA),  y = LDA, fill = enriched_group))+
    geom_bar(stat = 'identity', position = 'identity') +
     xlab('')+
     ylab('LDA Scores')+
     ggtitle('')+
     coord_flip()+
  theme_cleveland()+ 
  theme(legend.title = element_blank(),legend.position="right",legend.text =element_text(size=14,colour = 'black') )+ # 不显示图例的标题
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,face = 'italic',colour = 'black'))+
   ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)









stratified.pathway <- read.csv('input/humann2_pathabundance_cpm_stratified.tsv',header=T,sep ="\t",na.strings=c("","NA"))

stratified.pathway <- stratified.pathway[-which(stratified.pathway$pathway_ID%in%'UNINTEGRATED'),]

p.copri.pathway <- subset(stratified.pathway,species=='s__Prevotella_copri')

metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 2)

GRDB<- subset(stratified.pathway,pathway%in%unique(Pathway.lefse_3$pathway))
GRDB$genus <- as.character(GRDB$genus)
GRDB$species <- as.character(GRDB$species)




GRDB$species[is.na(GRDB$species)] <- GRDB$genus[is.na(GRDB$species)] #数据框species水平这一例的NA值用genus水平这一列的单元格替换。

GRDB.long <- melt(GRDB)

GRDB.long$seq_ID <- GRDB.long$variable
GRDB.long <- merge(GRDB.long,Bacteria.ra[,c(1:8,333)],by='seq_ID')

TOP.species <- data.frame('mean'=colMeans(Bacteria.ra[,c(9:332)]))

TOP.species <- subset(TOP.species,mean>0.3)



TOP.genus <- c('g__Prevotella','g__Faecalibacterium','g__Bacteroides','g__Bifidobacterium','g__Eubacterium')




mypal1 <- ggsci::pal_lancet( alpha = 1)(9) 
mypal2 <- ggsci::pal_npg( alpha = 1)(9)


GRDB.long <- subset(GRDB.long,GRDB.long$genus%in%TOP.genus)

GRDB.long$species <- gsub('s__','',GRDB.long$species,fixed = T)
GRDB.long <- subset(GRDB.long,GRDB.long$species%in%row.names(TOP.species))


ggplot(GRDB.long, aes(pathway, value, fill = species))+
geom_col(position = 'fill', width = 0.2) +
  theme_cleveland()+
  scale_y_continuous(expand=c(0,0))+
  theme(plot.title = element_text(hjust = 0.5)) + # 设置标题的位置在中间
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ #设置x.y标题上文本的名称
  theme(axis.text.x = element_text(size=14,colour = 'black',angle = 75,hjust = 1,vjust = 1),axis.text.y = element_text(size=14,colour = 'black')) + # 设置x.y坐标上文本大小
  theme(legend.position = 'top',legend.text = element_text(size=12,face = 'italic',colour = 'black')) +#设置图例文本
  theme(legend.title = element_blank()) +# 不显示图例的标题
  ylab("Percentage")+
  xlab('')+
  ggtitle('Contribution of species to pathway')+
  scale_fill_manual(values = c(mypal1,mypal2))




# 桑基图展示通路的贡献度




#整合分类和丰度的嵌套关系，构建桑基图 link 列表
link <- GRDB.long[,c('genus', 'species', 'value')]
colnames(link) <- c('source', 'target', 'abundance')




# family_genus <- genus[c('genus', 'species', 'value')]
# names(family_genus) <- c('source', 'target', 'abundance')


pathway_genus <- aggregate(GRDB.long$value, by = list(GRDB.long$pathway, GRDB.long$genus), FUN = sum)
names(pathway_genus) <- c('source', 'target', 'abundance')


genus_species <- aggregate(GRDB.long$value, by = list(GRDB.long$genus, GRDB.long$species), FUN = sum)  

names(genus_species) <- c('source', 'target', 'abundance')
                          
 
link_list <- rbind(pathway_genus, genus_species)




#构建 node 列表，并为 link 列表中的分类名称分配 id 指代
node_list <- reshape2::melt(GRDB.long,id = 'value')




node_list <- data.frame(GRDB.long[,c('pathway','genus','species','value')])

node_list <- melt(node_list,id.vars = 'value')
node_list <- node_list[,-1]


node_list <- node_list[!duplicated(node_list$value), ]
head(node_list)
 
link_list$IDsource <- match(link_list$source, node_list$value) - 1 
link_list$IDtarget <- match(link_list$target, node_list$value) - 1
head(link_list)


library(networkD3)

sankeyNetwork(Links = link_list, Nodes = node_list,
    Source = 'IDsource', Target = 'IDtarget', Value = 'abundance', 
    NodeID = 'value', NodeGroup = 'variable', 
    fontSize = 12, sinksRight = FALSE)





sankeyNetwork(Links = link_list, Nodes = node_list,
    Source = 'IDsource', Target = 'IDtarget',
    Value = 'abundance', 
    NodeID = 'value', NodeGroup = 'variable', 
    nodePadding = 50, nodeWidth = 20, fontSize = 12,  height = 300, width = 800)

P1 <- sankeyNetwork(Links = link_list, Nodes = node_list,
    Source = 'IDsource', Target = 'IDtarget', Value = 'abundance', 
    NodeID = 'value', NodeGroup = 'variable', 
    fontSize = 0, sinksRight = FALSE)



saveNetwork(P1,"output/sankey.html")








```


# Figure 6D and Figure S6

```{r,echo=T}


pathway <- read.table('input/humann2_pathabundance_cpm_unstratified.tsv',header = T,sep='\t',row.names = 1)

tax <- read.csv('input/pathway.tax.csv',header = T)

pathway$pathway_ID <- row.names(pathway)
pathway <- merge(tax,pathway,by='pathway_ID')

row.names(pathway) <- pathway$pathway


pathway <- as.data.frame(t(pathway[,-c(1:4)]))

pathway <- pathway[,unique(p.copri.pathway$pathway)]

pathway$seq_ID <- rownames(pathway)
pathway <- merge(pathway,Bacteria.ra[,c(1:8,333,263)],by='seq_ID')

rownames(pathway) <- pathway$seq_ID



pathway.long <- melt(pathway,id.vars = colnames(pathway[,c(1,9:17)]))




ggplot(data=pathway.long, aes(y=pathway.long$Prevotella_copri,x=pathway.long$value,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=pathway.long, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle(NULL)+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)+
  facet_wrap(~variable)


pathway.long.1 <- subset(pathway.long,variable%in%c(' adenosine ribonucleotides de novo biosynthesis',' guanosine ribonucleotides de novo biosynthesis'))



ggplot(data=pathway.long.1, aes(y=pathway.long.1$Prevotella_copri,x=pathway.long.1$value,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=pathway.long.1, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle(NULL)+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)+
  facet_wrap(~variable)

```
