---
output:
  html_document: default
  pdf_document: default
---


# Figure S1

```{r,echo=T}
library(ggplot2)
library(ggpubr)
library(reshape2)
library(vegan)
library(ggsci)

genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)

genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)
genus.ra$ID <- rownames(genus.ra)
metadata <- read.csv('input/tiv16s.all.BMI.metadata.csv',header=T)
metadata <- subset(metadata,type%in%'fecal'&region%in%c('rural'))
metadata$relocation.years <- factor(metadata$relocation.years,levels = c('Baseline','Year1','Year2'))
genus.ra <- merge(metadata,genus.ra,by='ID')

genus.ra <- genus.ra[!duplicated(genus.ra$ID.1),]

# genus.ra <- subset(genus.ra,status=='pre')







met <- read.csv('input/TIV_NEW_MET.csv',header = T)
met <- merge(genus.ra[,c(1:2,12)],met,by='ID.1')
rownames(met) <- met$ID


rownames(genus.ra) <- genus.ra$ID

genus.ra <- genus.ra[rownames(met),]
genus.ra <- genus.ra[,-c(1:13)]






feces.bray <- as.matrix(vegdist(genus.ra,"bray"))




feces.met <- met[,c(3,6,8,9,13:15)]

feces.met <- na.omit(feces.met)

feces.bray <- feces.bray[rownames(feces.met), rownames(feces.met)] 


feces.adonis <- data.frame(matrix(nrow = 7,ncol=6))

for(i in 1:7)
{
  feces.adonis[i,] <- adonis(feces.bray~feces.met[,i])$aov.tab[1,]
  print(feces.adonis)
  
}



adonis.result<-adonis(feces.bray~feces.met$relocation.years)$aov.tab[1,]

colnames(feces.adonis) <- colnames(adonis.result)
rownames(feces.adonis) <- colnames(feces.met)





feces.adonis$significance <- car::recode(feces.adonis$`Pr(>F)`,'0:0.05="Yes";0.05:1="No" ')

feces.adonis <- feces.adonis[order(feces.adonis$R2,decreasing = F),]

feces.adonis$factor <- rownames(feces.adonis)

feces.adonis$factor <- factor(feces.adonis$factor,levels = as.character(feces.adonis$factor))


feces.adonis$factor <- c('Sex','Urbanization','Family number',
                         'Altitude','BMI','City Location in TAR','Movement years')

feces.adonis$factor <- factor(feces.adonis$factor,levels =c('Sex','Urbanization','Family number',
                         'Altitude','BMI','City Location in TAR','Movement years') )


ggplot(feces.adonis, aes(x = factor, y = R2*100,fill=significance)) + 
    geom_bar(stat = "identity", width = 1,position=position_dodge(0.2),color="black",fill="#E64B35E5")+
  coord_flip()+
    theme_classic()+ 
    theme(legend.position="right", 
          legend.title=element_text(colour="black",size=14),
          legend.text = element_text(colour="black",size=14,),
          # legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), 
          axis.text.y=element_text(size=14,colour="black"), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14),
          plot.title = element_text(size=16,face="bold",hjust = 0.5), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  labs(y='Explained variation(%)', x="")+ 
    ggsci::scale_fill_npg(alpha = 0.8)+
    scale_y_continuous(expand =c(0,0))+
  ggtitle('Factors affecting community structure')

```

# Figure S2
```{r}
library(ggplot2)
library(microbiome)
library(RColorBrewer)
library(patchwork)
set.seed(123)

genus<- read.csv('input/genus.csv',header = T,row.names = 1)


rownames(genus) <- gsub('-','',rownames(genus),fixed = T)
rownames(genus) <- gsub('.','',rownames(genus),fixed = T)
rownames(genus) <- gsub(' ','',rownames(genus),fixed = T)
rownames(genus) <- gsub('(','',rownames(genus),fixed = T)
rownames(genus) <- gsub(')','',rownames(genus),fixed = T)


metadata <- read.csv('input/tiv16s.all.BMI.metadata.csv',header=T)
metadata <- subset(metadata,type%in%'fecal'&region%in%c('rural'))

genus <- genus[,colnames(genus)%in%c(metadata$ID)] 

genus <- genus[rowSums(genus)>10000,]


metadata_Baseline <- subset(metadata,relocation.years%in%'Baseline')
rownames(metadata_Baseline) <- metadata_Baseline$ID
genus_Baseline <- as.matrix(genus[,metadata_Baseline$ID])




metadata_Year1 <- subset(metadata,relocation.years%in%'Year1')
rownames(metadata_Year1) <- metadata_Year1$ID
genus_Year1 <- as.matrix(genus[,metadata_Year1$ID])



metadata_Year2 <- subset(metadata,relocation.years%in%'Year2')
rownames(metadata_Year2) <- metadata_Year2$ID
genus_Year2<- as.matrix(genus[,metadata_Year2$ID])



pseq.Baseline<- microbiome::transform(genus_Baseline, "compositional")
pseq.Year1<- microbiome::transform(genus_Year1, "compositional")
pseq.Year2<- microbiome::transform(genus_Year2, "compositional")




taxa.standard_Baseline <- core_members(pseq.Baseline, detection = 1e-2, prevalence = 50/100)
taxa.standard_Year1 <- core_members(pseq.Year1, detection = 1e-2, prevalence = 50/100)
taxa.standard_Year2<- core_members(pseq.Year2, detection = 1e-2, prevalence = 50/100)


pseq.Baseline.c <- pseq.Baseline[taxa.standard_Baseline,]
pseq.Year1.c <- pseq.Year1[taxa.standard_Year1,]
pseq.Year2.c <- pseq.Year2[taxa.standard_Year2,]



prevalences <- seq(0, 1, .2)
detections <- c(0.001,0.005,0.01,0.02,0.04,0.08,0.10,0.2,0.3,0.4,0.6)*100


a <- plot_core(pseq.Baseline.c*100, plot.type = "heatmap", 
          prevalences = prevalences,
                detections = detections,
                colours = rev(brewer.pal(1, "Spectral")),
                # colours = brewer.pal(1,"YlGnBu"),
                horizontal = F)+xlab('Relative abundance%')+
                theme(axis.text.x = element_text(size=14,color = 'black',family = 'Arial'),    
                      axis.title.x=element_text(size=14,color = 'black',family = 'Arial'),
                      axis.text.y = element_text(size=14,face = 'italic',color = 'black',family = 'Arial')) +
                theme(title=element_text(size=14,color = 'black',family = 'Arial'),
                      legend.text  = element_text(size=10,color = 'black',family = 'Arial'),
                      legend.title = element_text(size=14,color = 'black',family = 'Arial'))+
                ggtitle('Baseline')



b <- plot_core(pseq.Year1.c*100, plot.type = "heatmap", 
          prevalences = prevalences,
                detections = detections,
                colours = rev(brewer.pal(1, "Spectral")),
                # colours = brewer.pal(1,"YlGnBu"),
                horizontal = F)+xlab('Relative abundance%')+
                theme(axis.text.x = element_text(size=14,color = 'black',family = 'Arial'),    
                      axis.title.x=element_text(size=14,color = 'black',family = 'Arial'),
                      axis.text.y = element_text(size=14,face = 'italic',color = 'black',family = 'Arial')) +
                theme(title=element_text(size=14,color = 'black',family = 'Arial'),
                      legend.text  = element_text(size=10,color = 'black',family = 'Arial'),
                      legend.title = element_text(size=14,color = 'black',family = 'Arial'))+
                ggtitle('Year1')






c <- plot_core(pseq.Year2.c*100, plot.type = "heatmap", 
          prevalences = prevalences,
                detections = detections,
                colours = rev(brewer.pal(1, "Spectral")),
                # colours = brewer.pal(1,"YlGnBu"),
                horizontal = F)+xlab('Relative abundance%')+
                theme(axis.text.x = element_text(size=14,color = 'black',family = 'Arial'),    
                      axis.title.x=element_text(size=14,color = 'black',family = 'Arial'),
                      axis.text.y = element_text(size=14,face = 'italic',color = 'black',family = 'Arial')) +
                theme(title=element_text(size=14,color = 'black',family = 'Arial'),
                      legend.text  = element_text(size=10,color = 'black',family = 'Arial'),
                      legend.title = element_text(size=14,color = 'black',family = 'Arial'))+
                ggtitle('Year2')

a/b/c

```


#Figure S3


```{r,echo=T}

genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)
genus.ra$ID <- rownames(genus.ra)
metadata <- read.csv('input/tiv16s.all.BMI.metadata.csv',header=T)
metadata <- subset(metadata,type%in%'fecal'&region%in%c('rural'))
metadata$relocation.years <- factor(metadata$relocation.years,levels = c('Baseline','Year1','Year2'))
genus.ra <- merge(metadata,genus.ra,by='ID')




ggplot(data=genus.ra,aes(x=Prevotella,y=Bacteroides))+ geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=genus.ra, method = "spearman")+
labs(x = "Prevotella (%)", y = "Bacteroides (%)")+
  theme_cleveland()+ 
  ylim(0,55)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,face='italic',colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))






metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T)
rural_meta <- subset(metadata_meta,region=='rural')

KO <- read.table('input/humann2_genefamilies_cpm_ko_stratified.1.tsv',header = T,sep='\t')


KO <- KO[-which(KO$genus%in%'unclassified'),]




kegg_level <- read.csv('input/kegg_ko_levels.csv',header = 1)

kegg_level2 <- kegg_level[,c(4,8)]

kegg_level2 <- kegg_level2[!duplicated(kegg_level2),]

kegg_level2.cpm <- merge(kegg_level2,KO,by='KID')

kegg_level2.cpm.1 <- aggregate(kegg_level2.cpm[,-c(1:4)],list(kegg_level2.cpm$Level2_pathway_name,kegg_level2.cpm$species),sum)



P.B <- subset(kegg_level2.cpm.1,Group.2%in%c('s__Prevotella_copri','s__Bacteroides_ovatus'))
P.B <- melt(P.B)
P.B$seq_ID <- P.B$variable
P.B.long <- merge(metadata_meta,P.B,by='seq_ID',all=T)
P.B.long <- subset(P.B.long,region%in%'rural')

P.B.long <- subset(P.B.long,Group.1%in%c('Carbohydrate metabolism','Metabolism of cofactors and vitamins','Lipid metabolism','Translation','Protein metabolism', 'Transcription','Energy metabolism'))




P.B.long.1 <- dcast(P.B.long,seq_ID+region+Group.1+relocation.years~Group.2)



ggplot(data=P.B.long.1, aes(y=P.B.long.1$s__Bacteroides_ovatus,x=P.B.long.1$s__Prevotella_copri))+
  facet_wrap(~Group.1,scales = 'free')+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=P.B.long.1, method = "spearman")+
labs(x = "Copies per million contributed by P.copri",
     y="Copies per million contributed by B. ovatus")+
  theme_classic()+ 
  theme(panel.grid=element_blank(),
    strip.text =element_text(size=12,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_y_continuous(expand = c(0,0))




```