
###颜色
```{r}

mypal1 <- ggsci::pal_lancet( alpha = 0.8)(9) 
mypal2 <- ggsci::pal_lancet( alpha = 0.8)(9)
mypal3 <- ggsci::pal_aaas(alpha = 0.8)(9)

```

## Figure 4A
                    
```{r,echo = TRUE}
library(reshape2)
library(ggplot2)
library(ggpubr)
library(ggbiplot)

mypal1 <- ggsci::pal_lancet( alpha = 1)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.5)(9)

mypal3 <- ggsci::pal_d3( alpha = 0.5)(9)

mypal4 <- ggsci::pal_npg( alpha = 1)(9)


met <- read.csv('input/metadata.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('input/neg_ALL_sample_data_In vitro feeding experimental metabolome.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.8)

tax <- count[,1:18]

count <- count[,19:78]
count <- as.data.frame(t(count))


met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("0H","6H","12H","24H","48H")) 

pca <- prcomp(count, scale. = TRUE)



df_r<- as.data.frame(pca$rotation *100) #查看各变量对于PCA的贡献
df_r$feature<- row.names(df_r)















pca.data <- as.data.frame(pca$x)
pca.data$Group <- met$Group
pca.data$Time <- met$Time



ggscatter(pca.data,x='PC1',y='PC2',color = 'Time',shape='Group',ellipse = T)+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black',angle = 90))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black'),legend.position = 'right') +
  theme(legend.title = element_text(size=14,colour = 'black'))+
  scale_color_manual(values = c(mypal4))+
   labs(title = 'Metabolite phenotype',x=paste("PC1(28.5%)"),y=paste("PC2(6.5%)"))



```
### Figure 4B-1
                     
```{r,echo = TRUE}

library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
met <- read.csv('input/metadata.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('input/pos_ALL_sample_data_In vitro feeding experimental metabolome.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.8)

count <- subset(count,count$`Class I`%in%c('Carbohydrates and Its metabolites'))



tax <- count[,1:18]

count <- count[,19:78]
count <- as.data.frame(t(count),check.names=F)


met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("0H","6H","12H","24H","48H")) 

count <- data.frame(met,count,check.names=F)

count.long <- melt(count)




p <- compare_means(
  value~Group,
  data=count.long,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time','variable'),
  p.adjust.method = "holm")



p1 <- subset(p,p.format<0.05)


count.1 <- count[,as.character(unique(p1$variable))]
count.1 <- data.frame(met,count.1,check.names=F)
count.1.long <- melt(count.1)


library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

count.1.long %>%
  mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time,y =value,
           group=Group,color=Group)) +  
  facet_wrap(~variable,scales = 'free_y')+
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(y = "",x='Time')



# 可能促进PC生长的糖

count.2.long <- subset(count.1.long,count.1.long$variable%in%c('Sucrose'))

count.2.long %>%
  mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time,y =value,
           group=Group,color=Group)) +  
  facet_wrap(~variable,scales = 'free')+
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(y = "",x='Time')





```

### Figure 4B-2
                     
```{r,echo = TRUE}

library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
met <- read.csv('input/metadata.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('input/neg_ALL_sample_data_In vitro feeding experimental metabolome.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.8)

count <- subset(count,count$`Class I`%in%c('Carbohydrates and Its metabolites'))



tax <- count[,1:18]

count <- count[,19:78]
count <- as.data.frame(t(count),check.names=F)

met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("0H","6H","12H","24H","48H")) 

count <- data.frame(met,count,check.names=F)

count.long <- melt(count)




p <- compare_means(
  value~Group,
  data=count.long,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time','variable'),
  p.adjust.method = "holm")



p1 <- subset(p,p.format<0.05)


count.1 <- count[,as.character(unique(p1$variable))]
count.1 <- data.frame(met,count.1,check.names=F)
count.1.long <- melt(count.1)


library(tidyverse)
library(ggsci)
library(patchwork)
# 可能促进PC生长的糖

count <- read.csv('input/neg_ALL_sample_data_In vitro feeding experimental metabolome.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.8)

count <- count[c('Trehalose','D-Maltose','alpha-D-Glucose','Cellobiose'),]


count <- count[,19:78]
count <- as.data.frame(t(count),check.names=F)

met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("0H","6H","12H","24H","48H")) 


count <- data.frame(met,count,check.names=F)

count.2.long <- melt(count)



count.2.long %>%
  mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time,y =value,
           group=Group,color=Group)) +  
  facet_wrap(~variable,scales = 'free')+
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(y = "",x='Time')





```





## Figure 4D-1
```{r,echo=T}
library(reshape2)
library(ggplot2)
library(ggpubr)

qpcr.16s <- read.csv('input/P. copri mouse colonization experiment-16S absolute quantification results.csv',header = T)



qpcr.16s$copies <- log10(as.numeric(qpcr.16s$X16s拷贝数.copies.mg样本.))

qpcr.16s$Days <- factor(qpcr.16s$Days,levels = c('Day-7','Day0','Day4','Day7','Day8','Day16'))

qpcr.16s$Days.1 <- gsub("Day","",qpcr.16s$Days,fixed = T)
qpcr.16s$Days.1 <- as.numeric(qpcr.16s$Days.1)



ggplot(qpcr.16s,aes(x=Days.1,y=copies)) +
   geom_smooth(method = 'loess',se = F,aes(color=group))+
  geom_jitter(width=0.08,shape = 20,size=2,aes(color=group))+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(16s Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.6)+
  scale_x_continuous(name="Days", limits=c(-7, 20),breaks = c(-7,0,4,8,16))


```



## Figure 4D-2
```{r,echo=T}
library(reshape2)
library(ggplot2)
library(ggpubr)

qpcr.pc <- read.csv('input/P. copri mouse colonization experiment-PC absolute quantification results.csv',header = T)



qpcr.pc$pc <- log10(as.numeric(qpcr.pc$P.copri拷贝数.copies.mg样本.))



qpcr.pc$Days <- factor(qpcr.pc$Days,levels = c('Day-7','Day0','Day4','Day7','Day8','Day16'))






qpcr.pc$Days.1 <- gsub('Day','',qpcr.pc$Days,fixed = T)

qpcr.pc$Days.1 <- as.numeric(qpcr.pc$Days.1)

qpcr.pc <- qpcr.pc[qpcr.pc$Days.1!=7,]







ggplot(qpcr.pc,aes(x=Days.1,y=pc)) +
   geom_smooth(method = 'loess',se = T,aes(group=group,fill=group,color=group))+
  geom_jitter(width=0.08,shape = 20,size=2,aes(color=group))+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(P. copri Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.6)+
  scale_x_continuous(name="Days", limits=c(-1, 20),breaks = c(0,4,8,16))




```


### Figure 4E-1
                     
```{r,echo = TRUE}

library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
met <- read.csv('input/metadata.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('input/neg_ALL_sample_data_feces_metabolome of mice.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.6)

count <- subset(count,count$`Class I`%in%c('Carbohydrates and Its metabolites'))





tax <- count[,1:18]

count <- count[,19:45]
count <- as.data.frame(t(count),check.names=F)


met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("day0","day4","day8")) 

count <- data.frame(met,count,check.names=F)

count.long <- melt(count)




p <- compare_means(
  value~Group,
  data=count.long,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time','variable'),
  p.adjust.method = "holm")



p1 <- subset(p,p.format<0.05)


count.1 <- count[,as.character(unique(p1$variable))]
count.1 <- data.frame(met,count.1,check.names=F)
count.1.long <- melt(count.1)


library(tidyverse)
library(ggsci)
library(patchwork)


# 可能促进PC生长的糖

count.2.long <- subset(count.1.long,count.1.long$variable%in%c('Trehalose','D-Maltose','alpha-D-Glucose','Cellobiose','Melezitose','D-Xylose','Scleroglucan','N-Acetyl-D-glucosamine','Verbascose','Gentianose','Lacto-N-triaose'))

count.2.long %>%
  mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time,y =value,
           group=Group,color=Group)) +  
  facet_wrap(~variable,scales = 'free')+
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(y = "",x='Time')

```

### Figure 4E-2
                     
```{r,echo = TRUE}

library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
met <- read.csv('input/metadata.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('input/pos_ALL_sample_data_feces_metabolome of mice.csv',header=T,row.names=3,check.names = F)

count <- subset(count,count$score>0.6)

count <- subset(count,count$`Class I`%in%c('Carbohydrates and Its metabolites'))





tax <- count[,1:18]

count <- count[,19:45]
count <- as.data.frame(t(count),check.names=F)


met <- met[row.names(count),]
met$Time <-factor(met$Time,levels = c("day0","day4","day8")) 

count <- data.frame(met,count,check.names=F)

count.long <- melt(count)




p <- compare_means(
  value~Group,
  data=count.long,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time','variable'),
  p.adjust.method = "holm")



p1 <- subset(p,p.format<0.05)


count.1 <- count[,as.character(unique(p1$variable))]
count.1 <- data.frame(met,count.1,check.names=F)
count.1.long <- melt(count.1)


library(tidyverse)
library(ggsci)
library(patchwork)



# 可能促进PC生长的糖

count.2.long <- subset(count.1.long,count.1.long$variable%in%c('Maltitol',"3'-Sialyllactose","Kojibiose","Vicianose","Paromomycin"))

count.2.long %>%
  mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time,y =value,
           group=Group,color=Group)) +  
  facet_wrap(~variable,scales = 'free')+
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(y = "",x='Time')

```
