---
title: "Figure S7"
output: html_document

---
```{r setup, iNegativelude=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 配色
```{r global_options, iNegativelude=FALSE}
library(ggplot2)
library(ggsci)

mypal1 <- ggsci::pal_lancet( alpha = 1)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.5)(9)



```

# Figure S7

```{r global_options, iNegativelude=FALSE}
omv.result <- read.csv('input/OMV-多糖-基于RCM-实验结果23.7.5.csv',header=T)



library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)


omv <- subset(omv.result,omv.result$Group%in%c("Pc","Pc+Pc omv","Pc+Ls omv","Pc+Bp omv"))



p.omv<- compare_means(
  OD600~Group,
  data=omv,
  method = "t.test",
  paired = FALSE,
  group.by =c('Incubation.time'),
  p.adjust.method = "holm")




library(ggsci)
library(patchwork)
library(ggpubr)

omv %>%
  mutate(Incubation.time=as.factor(Incubation.time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Incubation.time,y =OD600,
           group=Group,color=Group)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = NULL))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')



ggplot(omv, aes(x=Incubation.time, y =OD600,group=Group,color=Group)) + 
  geom_point(position = position_jitter(width = 0.4, height = 0.05, seed = 123)) +
  stat_smooth(method="loess",span = 0.5, se = TRUE, level = 0.95, aes(x=Incubation.time, y =OD600,group=Group,color=Group))+
   theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = NULL))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  stat_summary(fun.y="mean",geom="point",size=3) +      
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)



a <- subset(omv.result,omv.result$Group%in%c("Pc","Pc+Pc omv"))

b <- subset(omv.result,omv.result$Group%in%c("Pc","Pc+Bp omv"))

c <- subset(omv.result,omv.result$Group%in%c("Pc","Pc+Ls omv"))


a1 <- ggplot(a, aes(x=Incubation.time, y =OD600,group=Group,color=Group)) + 
  geom_point(position = position_jitter(width = 0.4, height = 0.05, seed = 123)) +
  stat_smooth(method="loess",span = 0.5, se = TRUE, level = 0.95, aes(x=Incubation.time, y =OD600,group=Group,color=Group))+
   theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = NULL))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  stat_summary(fun.y="mean",geom="point",size=3) +      
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)

b1 <- ggplot(b, aes(x=Incubation.time, y =OD600,group=Group,color=Group)) + 
  geom_point(position = position_jitter(width = 0.4, height = 0.05, seed = 123)) +
  stat_smooth(method="loess",span = 0.5, se = TRUE, level = 0.95, aes(x=Incubation.time, y =OD600,group=Group,color=Group))+
   theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = NULL))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  stat_summary(fun.y="mean",geom="point",size=3) +      
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)

c1 <- ggplot(c, aes(x=Incubation.time, y =OD600,group=Group,color=Group)) + 
  geom_point(position = position_jitter(width = 0.4, height = 0.05, seed = 123)) +
  stat_smooth(method="loess",span = 0.5, se = TRUE, level = 0.95, aes(x=Incubation.time, y =OD600,group=Group,color=Group))+
   theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = NULL))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  stat_summary(fun.y="mean",geom="point",size=3) +      
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)


a1
b1
c1

library(patchwork)

a1+b1+c1

```

