

## library

```{r,echo=T,warning=FALSE}

library(tidytree)
library(ggplot2)
library(ggtree) 
library(ggtreeExtra)
library(ggstar)
library(reshape2)
library(ggpubr)
library(statnet)
library(circlize)
library(vegan)


mypal1 <- ggsci::pal_lancet( alpha = 0.8)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.8)(9)
mypal3 <- ggsci::pal_aaas(alpha = 0.8)(9)



```




## Figure S5

```{r,echo=T,warning=FALSE}

metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)
species <- read.table('input/metaphlan2_merged_species.txt',header = T,sep='\t')
tax <- read.table('input/tax.txt',header = T,sep='\t')

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species.tax <- species.tax[!duplicated(species.tax$species), ] # 去重复
species <- merge(species.tax,species,by='species')

Bacteria <- subset(species,kingdom=='Bacteria')
rownames(Bacteria) <- Bacteria$species

Bacteria.ra <- Bacteria[,c(8:114)]
Prevotella_copri <- t(Bacteria.ra['Prevotella_copri',])

shannon=data.frame('shannon'=diversity(t(Bacteria.ra),"shannon")) 
shannon$Prevotella_copri <- Prevotella_copri
shannon$seq_ID <- rownames(shannon)
shannon <- merge(shannon,metadata_meta,by='seq_ID')


ggplot(data=shannon, aes(y=shannon,x=Prevotella_copri))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=shannon, method = "spearman")+
labs(y = "shannon", x = "P.copri (%)")+
  theme_cleveland()+ xlim(0,60)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14), axis.title.y=element_text(size=14,face='italic'))+ 
  theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
  theme(legend.text = element_text(size=14)) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))





```


## Figure S7-S8

```{r}

species.ra <- read.csv('input/species.ra1_4.csv')

pathway <- read.csv('input/pathway.ra.1_4.csv',row.names = 1)

met <- read.csv('input/met_2021.csv')



species.ra <- merge(met,species.ra,by='X')
stool.ra <- subset(species.ra,species.ra$body_site=='stool')


colnames(stool.ra) <- gsub(' ','_',colnames(stool.ra),fixed = T)
colnames(stool.ra) <- gsub('[','',colnames(stool.ra),fixed = T)
colnames(stool.ra) <- gsub(']','',colnames(stool.ra),fixed = T)
colnames(stool.ra) <- gsub('.','',colnames(stool.ra),fixed = T)


row.names(stool.ra) <- stool.ra$X



pathway <- pathway[stool.ra$X,]


cor.p <- matrix(nrow=ncol(pathway),ncol=1)

# 求相关系数
for(i in 1:ncol(pathway))
    {cor.p[i,]<- cor.test(stool.ra$s__Prevotella_copri,pathway[,i],method = 'spearman')$p.value
  }

rownames(cor.p) <- colnames(pathway)


cor.r <- matrix(nrow=ncol(pathway),ncol=1)

for(i in 1:ncol(pathway))
    {cor.r[i,]<-cor.test(stool.ra$s__Prevotella_copri,pathway[,i],method = 'spearman')$estimate
  }

rownames(cor.r) <- colnames(pathway)
#cor.r[cor.p>0.05|abs(cor.r)<0.2] = NA
cor.r <- as.data.frame(cor.r)
cor.r$pathway <- rownames(cor.r)










pathway.a <- grep(c('adenosine'),cor.r$pathway)
pathway.g <- grep(c('guanosine'),cor.r$pathway)
pathway.i <- grep(c('inosine'),cor.r$pathway)


pathway.nc <- pathway[,c(pathway.a,pathway.g,pathway.i)]


cor.r.1 <- cor.r[c(pathway.a,pathway.g,pathway.i),]



stool.ra$PC <- car::recode(stool.ra$s__Prevotella_copri,"5:100='HPC';else='LPC'")


stool.ra$Bo <- car::recode(stool.ra$s__Bacteroides_ovatus,"5:100='HBo';else='LBo'")



stool.ra$Bv <- car::recode(stool.ra$s__Bacteroides_vulgatus,"5:100='HBv';else='LBv'")

library(ggpubr)
stool.ra <- subset(stool.ra,stool.ra$country%in%c('SWE'))
pathway.nc.1 <- pathway.nc[stool.ra$X,]

mean(stool.ra$s__Prevotella_copri)


table(stool.ra$study_name)
table(stool.ra$study_name,stool.ra$PC)


ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.7221..guanosine.ribonucleotides.de.novo.biosynthesis,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY7221-guanosine ribonucleotides 
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)




ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.7219..adenosine.ribonucleotides.de.novo.biosynthesis,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY7219-adenosine ribonucleotides 
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)








ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$SALVADEHYPOX.PWY..adenosine.nucleotides.degradation.II,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('Adenosine nucleotides degradation II')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.6126..superpathway.of.adenosine.nucleotides.de.novo.biosynthesis.II,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY6126-superpathway of adenosine 
          nucleotides denovo biosynthesisII')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.6609..adenine.and.adenosine.salvage.III,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY6609-adenine and adenosine salvage III')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)








ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.6608..guanosine.nucleotides.degradation.III,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY6608-guanosine nucleotides
          degradation III')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.6123..inosine.5..phosphate.biosynthesis.I,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY6123-inosine-5-phosphate biosynthesis I')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.5695..urate.biosynthesis.inosine.5..phosphate.degradation,
                          fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "P. copri (%)", x = "CPM")+
  ggtitle('PWY5695-urate biosynthesis 
          inosine-5-phosphate degradation')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)




ggplot(data=stool.ra, aes(y=stool.ra$s__Bacteroides_ovatus,x=1000*pathway.nc.1$PWY.7221..guanosine.ribonucleotides.de.novo.biosynthesis,fill=Bo,group=Bo,color=Bo))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "B.ovatus (%)", x = "CPM")+
  ggtitle('PWY7221-guanosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Bacteroides_ovatus,x=1000*pathway.nc.1$PWY.7219..adenosine.ribonucleotides.de.novo.biosynthesis,fill=Bo,group=Bo,color=Bo))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "B.ovatus (%)", x = "CPM")+
  ggtitle('7219-adenosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)



ggplot(data=stool.ra, aes(y=stool.ra$s__Bacteroides_vulgatus,x=1000*pathway.nc.1$PWY.7221..guanosine.ribonucleotides.de.novo.biosynthesis,fill=Bv,group=Bv,color=Bv))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "B.vulgatus(%)", x = "CPM")+
  ggtitle('PWY7221-guanosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)


ggplot(data=stool.ra, aes(y=stool.ra$s__Bacteroides_vulgatus,x=1000*pathway.nc.1$PWY.7219..adenosine.ribonucleotides.de.novo.biosynthesis,fill=Bv,group=Bv,color=Bv))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman")+
labs(y = "B.vulgatus(%)", x = "CPM")+
  ggtitle('7219-adenosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0,100)




ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=1000*pathway.nc.1$PWY.7219..adenosine.ribonucleotides.de.novo.biosynthesis,fill=PC,group=PC,color=PC))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman",)+
labs(y = "P. copri(%)", x = "CPM")+
  ggtitle('7219-adenosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0.01,100)





ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=pathway.nc.1$PWY.7219..adenosine.ribonucleotides.de.novo.biosynthesis*1000,fill="#E64B35E5",color="#E64B35E5"))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman",)+
labs(y = "P. copri(%)", x = "CPM")+
  ggtitle('7219-adenosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0.001,100)



ggplot(data=stool.ra, aes(y=stool.ra$s__Prevotella_copri,x=pathway.nc.1$PWY.7221..guanosine.ribonucleotides.de.novo.biosynthesis*1000,fill="#E64B35E5",color="#E64B35E5"))+ geom_point(size=2)+stat_smooth(method="lm",se=T)+
  stat_cor(data=stool.ra, method = "spearman",)+
labs(y = "P. copri(%)", x = "CPM")+
  ggtitle('7221-guanosine ribonucleotides \n
          denovo biosynthesis')+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
  scale_fill_manual(values = mypal1)+
  ylim(0.002,100)

```


# Figure S10

```{r,echo=F}

library(ggplot2)
library(ggpubr)
library(reshape2)
library(patchwork)

BC <- read.csv('input/Blood biochemical indicators.csv',header=T,row.names=3)

BC <- BC[,c(15:32)]



species <- read.table('input/kraken2_combined_unstratified_species.txt',header = T,sep='\t',quote = '')
tax <- read.table('input/kraken2_taxonomy.txt',header = T,sep='\t',quote = '')



species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species.tax <- species.tax[!duplicated(species.tax$species), ] # 去重复
species <- merge(species.tax,species,by='species')

Bacteria <- subset(species,kingdom=='k__Bacteria')
rownames(Bacteria) <- Bacteria$species

Bacteria<- Bacteria[,c(8:114)]
Bacteria <- as.data.frame(t(Bacteria))
Bacteria <- Bacteria[,colMeans(Bacteria)>500] 
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100


Bacteria.ra <-Bacteria.ra[rownames(BC),]
BC.ra <- data.frame(BC,'Prevotella.copri'=Bacteria.ra$Prevotella_copri)
BC.ra <- BC.ra[BC.ra$Prevotella.copri>5,]
BC.ra.long <- melt(BC.ra,id.vars = 'Prevotella.copri')




ggplot(data=BC.ra.long, aes(x=value,y=Prevotella.copri))+
  facet_wrap(~variable,scales = 'free_x')+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=BC.ra.long, method = "spearman")+
labs(y = "P.copri(%)")+
  theme_classic()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14), axis.title.y=element_text(size=14,face='italic'))+ 
  theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
  theme(legend.text = element_text(size=14)) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))

a <- ggplot(data=BC.ra, aes(x=BC.ra$TP,y=Prevotella.copri))+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=BC.ra, method = "spearman")+
labs(y = "P.copri(%)",x='TP (g/L)')+
  theme_classic()+ 
  ylim(0,80)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))

b <- ggplot(data=BC.ra, aes(x=BC.ra$ALB,y=Prevotella.copri))+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=BC.ra, method = "spearman")+
labs(y = "P.copri(%)",x='ALB (g/L)')+
  theme_classic()+ 
   ylim(0,80)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))



c <- ggplot(data=BC.ra, aes(x=BC.ra$TBIL,y=Prevotella.copri))+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=BC.ra, method = "spearman")+
labs(y = "P.copri(%)",x='TBIL (μmol/L)')+
  theme_classic()+ 
   ylim(0,80)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))

d <- ggplot(data=BC.ra, aes(x=BC.ra$DBIL,y=Prevotella.copri))+
  geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=BC.ra, method = "spearman")+
labs(y = "P.copri(%)",x='DBIL (μmol/L)')+
  theme_classic()+ 
   ylim(0,80)+
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,face='italic'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))



a+b+c+d


```