
###颜色
```{r}

mypal1 <- ggsci::pal_lancet( alpha = 0.8)(9) 
mypal2 <- ggsci::pal_lancet( alpha = 0.8)(9)
mypal3 <- ggsci::pal_aaas(alpha = 0.8)(9)

```



## Figure 6b

```{r,echo=T}
library(reshape2)
library(ggplot2)
library(ggpubr)

qpcr.16s<- read.csv('input/Pc动物定植实验-crz-16s定量结果.csv',header = T)



qpcr.16s$load<- log10(as.numeric(qpcr.16s$X16s拷贝数.copies.mg样本.))



qpcr.16s$Days <- factor(qpcr.16s$Days,levels = c('Day-7','Day0','Day4','Day8'))



p.16s<- compare_means(
  load~Days,
  data=qpcr.16s,
  method = "wilcox.test",
  paired = FALSE,
  group.by =c('group'),
  p.adjust.method = "holm")



ggplot(qpcr.16s,aes(x=group,y=load,fill=group)) +
    geom_boxplot(color='black',width=0.2,position=position_dodge(0.8),outlier.shape = NA)+ #绘制箱线图
  geom_jitter(width=0.08,shape = 20,size=2,color='black')+
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("1og10(P. copri Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
   stat_compare_means(label = "p.format",method = 'wilcox',comparisons = list(c("Control","P. copri"),c("Control","P. copri+Bo Sup"),c("P. copri","P. copri+Bo Sup")))+
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  facet_wrap(~Days)



qpcr.16s$Days.1 <- gsub('Day','',qpcr.16s$Days,fixed = T)

qpcr.16s$Days.1 <- as.numeric(qpcr.16s$Days.1)



ggplot(qpcr.16s,aes(x=Days.1,y=load)) +
   geom_smooth(method = 'loess',se = T,color='black')+
    geom_boxplot(aes(fill=Days),color='black',width=2,position=position_dodge(0.8),outlier.shape = NA)+ #绘制箱线图
  geom_jitter(width=0.08,shape = 20,size=2,color='black')+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="none", #不需要图例
          strip.text = element_text(colour="black",size=14,face='italic'),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(16s Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  ggtitle('Bacterial load')+
  facet_wrap(~group)






ggplot(qpcr.16s,aes(x=Days.1,y=load)) +
   geom_smooth(method = 'loess',se = T,aes(group=group,fill=group,color=group))+
  geom_jitter(width=0.08,shape = 20,size=2,aes(color=group))+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14,face='italic'),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(16s Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.6)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  ggtitle('Bacterial load')




```


## Figure 6c

```{r,echo=T}
library(reshape2)
library(ggplot2)
library(ggpubr)

qpcr.pc <- read.csv('input/Pc动物定植实验-crz-Pc定量结果.csv',header = T)



qpcr.pc$pc <- log10(as.numeric(qpcr.pc$P.copri拷贝数.copies.mg样本.))

qpcr.pc <- subset(qpcr.pc,Days!='Day16')

qpcr.pc$Days <- factor(qpcr.pc$Days,levels = c('Day-7','Day0','Day4','Day8'))



p.pc <- compare_means(
  pc~Days,
  data=qpcr.pc,
  method = "wilcox.test",
  paired = FALSE,
  group.by =c('group'),
  p.adjust.method = "holm")



ggplot(qpcr.pc,aes(x=group,y=pc,fill=group)) +
    geom_boxplot(color='black',width=0.2,position=position_dodge(0.8),outlier.shape = NA)+ #绘制箱线图
  geom_jitter(width=0.08,shape = 20,size=2,color='black')+
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("1og10(P. copri Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
   stat_compare_means(label = "p.format",method = 'wilcox',comparisons = list(c("Control","P. copri"),c("Control","P. copri+Bo Sup"),c("P. copri","P. copri+Bo Sup")))+
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  facet_wrap(~Days)



qpcr.pc$Days.1 <- gsub('Day','',qpcr.pc$Days,fixed = T)

qpcr.pc$Days.1 <- as.numeric(qpcr.pc$Days.1)



ggplot(qpcr.pc,aes(x=Days.1,y=pc)) +
   geom_smooth(method = 'loess',se = T,color='black')+
    geom_boxplot(aes(fill=Days),color='black',width=2,position=position_dodge(0.8),outlier.shape = NA)+ #绘制箱线图
  geom_jitter(width=0.08,shape = 20,size=3,color='black')+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="none", #不需要图例
          strip.text = element_text(colour="black",size=14,face='italic'),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(P. copri Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  facet_wrap(~group)+
  ggtitle('Absolute quantification of P. copri')






ggplot(qpcr.pc,aes(x=Days.1,y=pc)) +
   geom_smooth(method = 'loess',se = T,aes(group=group,fill=group,color=group))+
  geom_jitter(width=0.08,shape = 20,size=2,aes(color=group))+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("log10(P. copri Copies/mg feces)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.6)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  ggtitle('Absolute quantification of P. copri')




```
## Figure 6d

```{r,echo=T}

metadata_meta <- read.table('input/metadata.txt',header=T,sep='\t')
species <- read.table('input/kraken2_combined_unstratified_species.txt',header = T,sep='\t',quote = '',check.names = F)
tax <- read.table('input/kraken2_taxonomy.txt',header = T,sep='\t',quote = '')
P.tax <- subset(tax,tax$Genus%in%'Prevotella')




species.tax <- data.frame(Species=species$Species)
species.tax <- merge(tax,species.tax,by='Species')
species <- merge(species.tax,species,by='Species')

Bacteria <- subset(species,Kingdom=='k__Bacteria')
Bacteria$Species <- gsub('[','',fixed = T,Bacteria$Species)

Bacteria$Species <- gsub(']','',fixed = T,Bacteria$Species)

Bacteria$Species <- gsub("'","",fixed = T,Bacteria$Species)

rownames(Bacteria) <- Bacteria$Species
Bacteria<- Bacteria[,-c(1:7)]

Bacteria <- as.data.frame(t(Bacteria))
Bacteria <- Bacteria[,colMeans(Bacteria)>500] 
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100


P.ra <- Bacteria.ra[,P.tax$Species]



P.ra$Sample.id <- rownames(P.ra)
P.ra <- merge(metadata_meta,P.ra,by='Sample.id')
rownames(P.ra) <- P.ra$Sample.id
P.ra.long <- melt(P.ra)


P.ra.long$variable <- gsub('Prevotella_','P. ', P.ra.long$variable,fixed = T)

P.ra.long <- subset(P.ra.long,variable%in%c('P. copri'))

P.ra.long <- P.ra.long[-which(P.ra.long$Sample.id==c('P.copri+Boomv-Day4-5')),]



P.ra.long %>%
  mutate(Days=as.factor(Days)) %>% 
  group_by(variable) %>%
  ggplot(aes(x = Days,y =value,
           group=group,color=group)) +  
  
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
guides(color = guide_legend(title = NULL))+
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
   labs(y = "Abundance(%)",x=NULL)+
  ggtitle('P. copri colonization level \n by metagenomic assays')





p <- compare_means(
  value~group,
  data=P.ra.long,
  method = "wilcox",
  paired = FALSE,
  group.by =c('Days'),
  p.adjust.method = "holm")





P.ra.long$Days.1 <- car::recode(P.ra.long$Days,'"Day-7"=-7;
                                "Day0"=0;"Day4"=4;"Day8"=8')





ggplot(P.ra.long,aes(x=Days.1,y=value)) +
   geom_smooth(method = 'loess',se = T,color='black')+
    geom_boxplot(aes(fill=Days),color='black',width=2,position=position_dodge(0.8),outlier.shape = NA)+ #绘制箱线图
  geom_jitter(width=0.08,shape = 20,size=3,color='black')+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="none", #不需要图例
          strip.text = element_text(colour="black",size=14,face='italic'),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("Abundance(%)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 0.8)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  facet_wrap(~group)+
  ggtitle('P. copri colonization level \n by metagenomic assays')






ggplot(P.ra.long,aes(x=Days.1,y=value)) +
   geom_smooth(method = 'loess',se = T,aes(group=group,fill=group,color=group))+
  geom_jitter(width=0.08,shape = 20,size=2,aes(color=group))+
  
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("Abundance(%)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.6)+
  scale_x_continuous(name="Days", limits=c(-8, 10),breaks = c(-7,0,4,8))+
  ggtitle('P. copri colonization level \n by metagenomic assays')



P.ra.long <- subset(P.ra.long,P.ra.long$Sample.id!=c('P.copri+Sug-Pre3'))



ggplot(P.ra.long,aes(group,value,color=group,fill=group))+
  geom_bar(stat="summary",fun=mean,position="dodge",color='black')+ #绘制柱状图
  # geom_point(data=data,aes(G,value),size=2,pch=20,color="black")+#散点图
  stat_summary(geom = "errorbar", fun.data = 'mean_sd', width = 0.3,color="black")+#误差棒
  facet_grid(~Days,scales = 'free')+#分面
  ylim(0,0.2)+
geom_signif(comparisons = list(c("Control","P. copri"),
                                 c("P. copri","P. copri+Bo omv"),
                                 c("P. copri","P. copri+Sug")),# 设置需要比较的组
              map_signif_level = T, #是否使用星号显示
              test = "wilcox.test", ##计算方法
              y_position = c(0.1,0.12,0.14),#图中横线位置设置
              tip_length = c(c(0.01,0.01),
                             c(0.01,0.01),
                             c(0.01,0.01)),#横线下方的竖线设置
              size=0.8,color="black")+
  geom_jitter(width=0.15,shape = 20,size=2,color='black')+
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14,angle = 30,hjust = 1,vjust = 1), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("Abundance(%)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  ggtitle('P. copri colonization level \n by metagenomic assays')



ggplot(P.ra.long,aes(group,value,color=group,fill=group))+
  geom_bar(stat="summary",fun=mean,position="dodge",color='black')+ #绘制柱状图
  # geom_point(data=data,aes(G,value),size=2,pch=20,color="black")+#散点图
  stat_summary(geom = "errorbar", fun.data = 'mean_sd', width = 0.3,color="black")+#误差棒
  facet_grid(~Days,scales = 'free')+#分面
  ylim(0,0.15)+
  geom_jitter(width=0.15,shape = 20,size=2,color='black')+
    theme_cleveland()+ #背景变为白色
    theme(legend.position="right", #不需要图例
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          strip.text = element_text(colour="black",size=14),
          axis.text.x=element_text(colour="black",size=14,angle = 30,hjust = 1,vjust = 1), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
    ylab("Abundance(%)")+xlab("")+  #设置x轴和y轴的标题
  ggsci::scale_color_lancet(alpha = 1)+
  ggsci::scale_fill_lancet(alpha = 0.8)+
  ggtitle('P. copri colonization level by metagenomic assays')



```
