---
title: "Figure S2"
output:
  html_document: default
---
          
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,echo = F,include=F, results="hide"}
library(reshape2)
library(ggplot2)
library(ggpubr)
library(vegan)
library(tidyverse)
library(ggsci)
library(patchwork)

mypal1 <- ggsci::pal_npg( alpha = 0.9)(9) 
mypal2 <- ggsci::pal_lancet( alpha = 0.5)(9)
mycol <-ggsci::pal_npg( alpha = 0.8)(9) 


```
# Figure S2a

```{r,echo=T}
library(ggplot2)
library(ggpubr)
library(reshape2)
library(vegan)
library(ggsci)

genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)

genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)
genus.ra$ID <- rownames(genus.ra)
metadata <- read.csv('input/tiv16s.all.BMI.metadata.csv',header=T)
metadata <- subset(metadata,type%in%'fecal'&region%in%c('rural'))
metadata$relocation.years <- factor(metadata$relocation.years,levels = c('Baseline','Year1','Year2'))
genus.ra <- merge(metadata,genus.ra,by='ID')

genus.ra <- genus.ra[!duplicated(genus.ra$ID.1),]

# genus.ra <- subset(genus.ra,status=='pre')







met <- read.csv('input/TIV_NEW_MET.csv',header = T)
met <- merge(genus.ra[,c(1:2,12)],met,by='ID.1')
rownames(met) <- met$ID


rownames(genus.ra) <- genus.ra$ID

genus.ra <- genus.ra[rownames(met),]
genus.ra <- genus.ra[,-c(1:13)]






feces.bray <- as.matrix(vegdist(genus.ra,"bray"))




feces.met <- met[,c(3,6,8,9,13:15)]

feces.met <- na.omit(feces.met)

feces.bray <- feces.bray[rownames(feces.met), rownames(feces.met)] 


feces.adonis <- data.frame(matrix(nrow = 7,ncol=6))

for(i in 1:7)
{
  feces.adonis[i,] <- adonis(feces.bray~feces.met[,i])$aov.tab[1,]
  print(feces.adonis)
  
}



adonis.result<-adonis(feces.bray~feces.met$relocation.years)$aov.tab[1,]

colnames(feces.adonis) <- colnames(adonis.result)
rownames(feces.adonis) <- colnames(feces.met)





feces.adonis$significance <- car::recode(feces.adonis$`Pr(>F)`,'0:0.05="Yes";0.05:1="No" ')

feces.adonis <- feces.adonis[order(feces.adonis$R2,decreasing = F),]

feces.adonis$factor <- rownames(feces.adonis)

feces.adonis$factor <- factor(feces.adonis$factor,levels = as.character(feces.adonis$factor))


feces.adonis$factor <- c('Sex','Urbanization','Family number',
                         'Altitude','BMI','City Location in TAR','Movement years')

feces.adonis$factor <- factor(feces.adonis$factor,levels =c('Sex','Urbanization','Family number',
                         'Altitude','BMI','City Location in TAR','Movement years') )


ggplot(feces.adonis, aes(x = factor, y = R2*100,fill=significance)) + 
    geom_bar(stat = "identity", width = 1,position=position_dodge(0.2),color="black",fill="#E64B35E5")+
  coord_flip()+
    theme_classic()+ 
    theme(legend.position="right", 
          legend.title=element_text(colour="black",size=14),
          legend.text = element_text(colour="black",size=14,),
          # legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), 
          axis.text.y=element_text(size=14,colour="black"), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14),
          plot.title = element_text(size=16,face="bold",hjust = 0.5), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  labs(y='Explained variation(%)', x="")+ 
    ggsci::scale_fill_npg(alpha = 0.8)+
    scale_y_continuous(expand =c(0,0))+
  ggtitle('Factors affecting community structure')

```
### Figure S2b,S2c 
                     
```{r,echo = TRUE}



weighted_unifrac.dis <- read.table('input/distance-matrix-weighted-unifrac.tsv',header=T,row.names = 1,sep='\t')
metadata <- read.csv('input/tiv16s.all.BMI.metadata.csv',header=T,row.names=1)
metadata <- metadata[rownames(weighted_unifrac.dis),]
fecal.metadata <- subset(metadata,type%in%'fecal'&region%in%c('rural'))
fecal.metadata $relocation.years <- factor(fecal.metadata $relocation.years,levels = c('Baseline','Year1','Year2'))


fecal.weighted_unifrac <-  weighted_unifrac.dis[rownames(fecal.metadata), rownames(fecal.metadata)] # subset and reorder distance matrix





fecal.adon.result<-adonis(fecal.weighted_unifrac ~ fecal.metadata$relocation.years)$aov.tab


fecal.pcoa <-  cmdscale(fecal.weighted_unifrac, k=2, eig=T) # k is dimension,  eig is eigenvalues
fecal.points <-  as.data.frame(fecal.pcoa$points) # get coordinate string, format to dataframme
colnames(fecal.points) = c("x", "y") 
fecal.eig <- fecal.pcoa$eig

fecal.points <-  cbind(fecal.points, fecal.metadata[match(rownames(fecal.points), rownames(fecal.metadata)), ])










fecal.points$relocation.years <- as.character(fecal.points$relocation.years)
ggscatterhist(fecal.points,x="x",y="y",
              color="relocation.years",
              fill="relocation.years",
              palette=ggsci::pal_npg( alpha = 1)(3) ,
              shape=21,
              size=2,
              linetype = "solid",
              bins=30,
              margin.plot="boxplot",
              margin.params=list(fill="relocation.years",group="relocation.years",color='black'),
              margin.ggtheme=theme_light(),
              margin.space=F,
              main.plot.size=2,
              margin.plot.size=1,
              title="weighted_unifrac distance",
              legend="right",
  xlab =paste("PCoA 1 (", format(100 * fecal.eig[1] / sum(fecal.eig), digits=4), "%)", sep=""),
  ylab=paste("PCoA 2 (", format(100 * fecal.eig[2] / sum(fecal.eig), digits=4), "%)", sep=""),
    ggtheme=theme_cleveland()+  
    theme(plot.title = element_text(hjust = 0.5,size=15))+
    theme(axis.title.x =element_text(size=14,color = 'black'),
          axis.title.y=element_text(size=14,color = 'black'),
          axis.text.x = element_text(size=14,color = 'black'),
          axis.text.y = element_text(size=14,color = 'black'),
          legend.title = element_blank(),
          legend.text = element_text(size=14,color = 'black')))+
  annotate("text",x=0.3,y=0.2,size=5,label=paste('P < ',fecal.adon.result$`Pr(>F)`[1]),family="serif",fontface="italic",colour="black")








genus.ra <- read.csv('input/genus.ra.csv',header = T,row.names = 1)
genus.ra <-genus.ra[rownames(fecal.points),] 
genus.ra <- genus.ra[,colMeans(genus.ra)>1]


p.value=matrix(nrow=ncol(genus.ra),ncol=1)
for(i in 1:ncol(genus.ra))
{p.value[i,]<- cor.test(genus.ra[,i],fecal.points$`x`,method = 'spearman')$p.value
}

r=matrix(nrow=ncol(genus.ra),ncol=1)
for(i in 1:ncol(genus.ra))
{r[i,]<-cor.test(genus.ra[,i],fecal.points$`x`,method = 'spearman')$estimate
}

data <- cbind(p.value,r)
rownames(data) <- colnames(genus.ra)


r[p.value>0.05|abs(r)<0.3] = NA 
r <- as.data.frame(r)
rownames(r) <- colnames(genus.ra)
r$pcoa1 <- c('PCoA 1')
r$genus <- rownames(r)




r <- na.omit(r)



r$pcoa1 <- as.factor(r$pcoa1)
r$genus <- as.factor(r$genus)
r$r <- r$V1
r <- r[,-1]

col <- car::recode(r$r," 0:1 ='red';else='blue'") # 用颜色表示正负相关






r <- r[order(abs(r$r)),]

ggplot(data =r , mapping = aes(x = reorder(genus,abs(r)),  y = r))+
      geom_segment(aes(x = reorder(genus,abs(r) ), y =0, xend =reorder(genus,abs(r) ), yend = r),size=2,color = '#E64B35CC',)+
   geom_point(fill = '#E64B35CC', color = 'black',size=4,shape=21) +
     xlab(NULL)+
     ylab('Significant correlation with PCoA 1 ')+
     ylim(-1,1)+
     ggtitle('')+
     coord_flip()+
  geom_hline(yintercept = 0)+
  theme_cleveland()+ 
  theme(legend.title = element_blank(),legend.position="top",
        legend.text =element_text(size=14,colour="black"), )+ 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour="black"), axis.title.y=element_text(size=14,colour="black"))+ 
  theme(axis.text.x = element_text(size=14,colour="black"),axis.text.y = element_text(size=14,colour="black",face = 'italic'))


```

