---
title: "Figure 1"
---

## library
```{r,echo=TRUE}

library(ggplot2)
library(ggpubr)
library(reshape2)
library(vegan)
library(ggrepel)
library(magrittr)
library(dplyr)
library(plyr)
library(patchwork)
library(RColorBrewer)
library(car)
library(ggsci)
library(tidyverse)

```


## Figure 1b

```{r,echo=T}
metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)
species <- read.table('input/kraken2_combined_unstratified_species.txt',header = T,sep = '\t',quote = "")
tax <- read.table('input/kraken2_taxonomy.txt',header = T,sep = '\t',quote = "")
P.tax <- subset(tax,tax$genus%in%'Prevotella')

P.species <- merge(P.tax,species,by='species')

rownames(P.species) <- P.species$species

P.species<- P.species[,c(8:114)]

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species <- merge(species.tax,species,by='species')




P.species <- as.data.frame(t(P.species))



Bacteria <- subset(species,kingdom=='k__Bacteria')
rownames(Bacteria) <- Bacteria$species
Bacteria<- Bacteria[,c(8:114)]

Bacteria <- as.data.frame(t(Bacteria))
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100
Bacteria.ra$seq_ID <- rownames(Bacteria.ra)
Bacteria.ra <- merge(metadata_meta,Bacteria.ra,by='seq_ID')
rownames(Bacteria.ra) <- Bacteria.ra$seq_ID
Bacteria.ra <- Bacteria.ra[,-c(1:8)]
Bacteria.ra <- na.omit(Bacteria.ra)


Bacteria.ra.1 <- Bacteria.ra[,colMeans(Bacteria.ra)>0.5]
meta_rural <- subset(metadata_meta ,region=='rural')
Bacteria.ra.1 <- Bacteria.ra.1[meta_rural$seq_ID,] 


Bacteria.ra.2 <- Bacteria.ra[,colnames(P.species)]
Bacteria.ra.2 <- Bacteria.ra.2[,-1]
Bacteria.ra.2 <- Bacteria.ra.2[rownames(Bacteria.ra.1),]

Bacteria.ra.3 <- cbind(Bacteria.ra.1,Bacteria.ra.2)
Bacteria.ra.3.mean <- data.frame('mean'=colMeans(Bacteria.ra.3))

cor.p <- matrix(nrow=ncol(Bacteria.ra.3),ncol=1)


for(i in 1:ncol(Bacteria.ra.3))
    {cor.p[i,]<- cor.test(Bacteria.ra.3$Prevotella_copri,Bacteria.ra.3[,i],method = 'spearman')$p.value
  }

rownames(cor.p) <- colnames(Bacteria.ra.3)


cor.r <- matrix(nrow=ncol(Bacteria.ra.3),ncol=1)

for(i in 1:ncol(Bacteria.ra.3))
    {cor.r[i,]<- cor.test(Bacteria.ra.3$Prevotella_copri,Bacteria.ra.3[,i],method = 'spearman')$estimate
  }

rownames(cor.r) <- colnames(Bacteria.ra.3)

cor.r[cor.p>0.05|abs(cor.r)<0.3] = NA 

cor.r <- as.data.frame(cor.r)
cor.r$p <- cor.p
cor.r$p.copri <- c('P.copri')
cor.r$r <- cor.r$V1
cor.r$species <- rownames(cor.r)
cor.r <- na.omit(cor.r)
cor.r <- subset(cor.r,r<1)

Bacteria.ra.3.mean$species <- rownames(Bacteria.ra.3.mean)
Bacteria.ra.3.mean <- Bacteria.ra.3.mean[rownames(cor.r),]

Bacteria.ra.3.tax <- subset(species.tax,species%in%rownames(Bacteria.ra.3.mean))

Bacteria.ra.3.tax <- merge(Bacteria.ra.3.tax,cor.r,by='species')
Bacteria.ra.3.tax$species <- factor(Bacteria.ra.3.tax$species,levels = as.character(cor.r$species))

rownames(Bacteria.ra.3.tax) <- Bacteria.ra.3.tax$species
Bacteria.ra.3.tax <- Bacteria.ra.3.tax[order(Bacteria.ra.3.tax$species),]

cor.r$species.1 <- gsub("Prevotella_","P.",cor.r$species,fixed = T)
cor.r$species.1 <- gsub("Bacteroides_","B.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Ruminococcus_","R.",cor.r$species.1,fixed = T) 
cor.r$species.1 <- gsub("Akkermansia_","A.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Alistipes_","A.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Bifidobacterium_","B.",cor.r$species.1,fixed = T) 
cor.r$species.1 <- gsub("Blautia_","B.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Collinsella_","C.",cor.r$species.1,fixed = T)

cor.r$species.1 <- gsub("Dysosmobacter_","D.",cor.r$species.1,fixed = T) 
cor.r$species.1 <- gsub("Enterocloster_","E.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Faecalibacterium_","F.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Flavonifractor_","F.",cor.r$species.1,fixed = T) 
cor.r$species.1 <- gsub("Parabacteroides_","P.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Roseburia_","R.",cor.r$species.1,fixed = T)
cor.r$species.1 <- gsub("Ruthenibacterium_","R.",cor.r$species.1,fixed = T)



cor.r$genus <- Bacteria.ra.3.tax$genus
cor.r <- cor.r[order(cor.r$genus,decreasing = F),]

cor.r$species.1 <- factor(cor.r$species.1,levels = as.character(cor.r$species.1) ) 

mypal2 <- ggsci::pal_lancet( alpha = 0.6)(9) 
mypal1 <- ggsci::pal_npg( alpha = 0.8)(9)


library(ggpubr)
ggplot(data =cor.r , mapping = aes(x = species.1,  y = r))+
      geom_segment(aes(x = species.1, y =0, xend =species.1 , yend = r),size=2,color = '#E64B35CC',)+
   geom_point(aes(fill = genus), color = 'black',size=6,shape=21) +
     xlab(NULL)+
     ylab('Significant correlation with P.copri')+
     ylim(-1,1)+
     ggtitle('')+
  geom_hline(yintercept = 0)+
  theme_cleveland()+ 
  theme(legend.title = element_blank(),legend.position="top",
        legend.text =element_text(size=14,colour="black",face = 'italic'))+ 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour="black"), axis.title.y=element_text(size=14,colour="black"))+ 
  theme(axis.text.x = element_text(size=14,colour="black",face = 'italic',angle = 60,hjust = 1,vjust = 1),axis.text.y = element_text(size=14,colour="black"))+
  scale_fill_manual(values = c(mypal1,mypal2))




# 相关性热图

library(ggcorrplot)
corr <- round(cor(Bacteria.ra.3, method = 'spearman'), 1) 

p.mat <- cor_pmat(Bacteria.ra.3)

ggcorrplot(corr)

ggcorrplot(corr, 
           p.mat = p.mat, 
           hc.order = TRUE,
           insig = "blank"
                )+
  theme_cleveland()+ 
  guides(fill = guide_legend(title = 'spearman cor'))+
  theme(legend.title =element_text(size=14,colour="black") ,legend.position="right",
        legend.text =element_text(size=14,colour="black"))+ 
  theme(axis.text.x = element_text(size=14,colour="black",face = 'italic',angle = 45,vjust = 1,hjust = 1),axis.text.y = element_text(size=14,colour="black",face = 'italic'))




cor.r.1 <- subset(cor.r,cor.r$genus!='Prevotella')



library(ggpubr)
ggplot(data =cor.r.1 , mapping = aes(x = species.1,  y = r))+
      geom_segment(aes(x = species.1, y =0, xend =species.1 , yend = r),size=2,color = '#E64B35CC',)+
   geom_point(aes(fill = genus), color = 'black',size=6,shape=21) +
     xlab(NULL)+
     ylab('Significant correlation with P.copri')+
     ylim(-1,1)+
     ggtitle('')+
  geom_hline(yintercept = 0)+
  theme_cleveland()+ 
  theme(legend.title = element_blank(),legend.position="top",
        legend.text =element_text(size=14,colour="black",face = 'italic'))+ 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour="black"), axis.title.y=element_text(size=14,colour="black"))+ 
  theme(axis.text.x = element_text(size=14,colour="black",face = 'italic',angle = 60,hjust = 1,vjust = 1),axis.text.y = element_text(size=14,colour="black"))+
  scale_fill_manual(values = c(mypal1,mypal2))







```

## Figure 1c

```{r,echo=T}

metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)
species <- read.table('input/kraken2_combined_unstratified_species.txt',header = T,sep='\t',quote = '')
tax <- read.table('input/kraken2_taxonomy.txt',header = T,sep='\t',quote = '')
P.tax <- subset(tax,tax$genus%in%'Prevotella')




species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species <- merge(species.tax,species,by='species')
Bacteria <- subset(species,kingdom=='k__Bacteria')
rownames(Bacteria) <- Bacteria$species
Bacteria<- Bacteria[,c(8:114)]

Bacteria <- as.data.frame(t(Bacteria))
Bacteria <- Bacteria[,colMeans(Bacteria)>500] 
Bacteria.ra <- Bacteria/apply(Bacteria, 1, sum)*100


P.ra <- Bacteria.ra[,P.tax$species]
#P.ra <- P.ra[,-1]
#P.ra <- P.ra[-which(rownames(P.ra)%in%c('SeqCRZa_60','SeqCRZa_69','SeqCRZa_76')),]


P.ra$seq_ID <- rownames(P.ra)
P.ra <- merge(metadata_meta,P.ra,by='seq_ID')
rownames(P.ra) <- P.ra$seq_ID
P.ra.long <- melt(P.ra)

P.ra.long <- subset(P.ra.long,P.ra.long$region%in%'rural')

P.ra.long$variable <- gsub('Prevotella_','P. ', P.ra.long$variable,fixed = T)







P.ra.long$group2 <- car::recode(P.ra.long$variable,"'P. copri'='P. copri';else='Others'")

P.ra.long$group2 <- factor(P.ra.long$group2,levels = c('P. copri','Others'))

P.ra.long$relocation.years <- car::recode(P.ra.long$relocation.years,
                                          "'1M'='Baseline'; '1Y'='Y1'; '2Y'='Y2'")

P.ra.long %>%
  mutate(relocation.years=as.factor(relocation.years)) %>% 
  group_by(variable) %>%
  ggplot(aes(x = relocation.years,y =value,
           group=variable,color=variable)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  facet_wrap(~group2,scales = 'free_y')+
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = 'Prevotella'))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "Abundance(%)",x=NULL)



```
## Figure 1d

```{r,echo=T}


metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 1)
species <- read.table('input/metaphlan2_merged_species.txt',header = T,sep='\t')
tax <- read.table('input/tax.txt',header = T,sep='\t')

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species.tax <- species.tax[!duplicated(species.tax$species), ] 
species <- merge(species.tax,species,by='species')

Bacteria <- subset(species,kingdom=='Bacteria')
rownames(Bacteria) <- Bacteria$species

Bacteria.ra <- Bacteria[,c(8:114)]
Bacteria.ra <- as.data.frame(t(Bacteria.ra))

Bacteroides.tax <- subset(species.tax,genus%in%'Bacteroides')
Bacteroides.ra <- Bacteria.ra[,Bacteroides.tax$species]
Bacteroides.ra <- Bacteroides.ra[,colMeans(Bacteroides.ra)>0.1]

Bacteroides.ra$seq_ID <- rownames(Bacteroides.ra)
Bacteroides.ra <- merge(metadata_meta,Bacteroides.ra,by='seq_ID')
Bacteroides.ra.long <- melt(Bacteroides.ra)

Bacteroides.ra.long <- subset(Bacteroides.ra.long,region%in%'rural')

Bacteroides.ra.long$variable <- gsub("Bacteroides_","B. ",Bacteroides.ra.long$variable,fixed = T)

Bacteroides.ra.long$relocation.years <- car::recode(Bacteroides.ra.long$relocation.years,
                                          "'Baseline'='Baseline'; 'Year1'='Y1'; 'Year2'='Y2'")


B_ovatus <- subset(Bacteroides.ra.long,variable%in%'B. ovatus')





Bacteroides.ra.mean <- aggregate(Bacteroides.ra.long$value,list(Bacteroides.ra.long$relocation.years,Bacteroides.ra.long$variable),median)

colnames(Bacteroides.ra.mean) <- c('relocation.years','species','value')


Bacteroides.ra.mean <- dcast(Bacteroides.ra.mean, species~relocation.years)


Bacteroides.ra.mean <- Bacteroides.ra.mean[rowSums(Bacteroides.ra.mean[,-1])>0,]

Bacteroides.ra.mean <- Bacteroides.ra.mean[order(Bacteroides.ra.mean$Baseline,decreasing = T),]

Bacteroides.ra.mean$species <- factor(Bacteroides.ra.mean$species,levels = unique(as.character(Bacteroides.ra.mean$species)))



mypal1 <- ggsci::pal_lancet( alpha = 0.8)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.8)(9)

ggplot(melt(Bacteroides.ra.mean), aes(x=variable, y=value, fill=species)) + 
  geom_bar(stat = "identity", width=0.5, col='black')  + 
  geom_segment(data=Bacteroides.ra.mean %>% arrange(by=desc(species)) %>% mutate(Baseline=cumsum(Baseline)) %>% mutate(Y1=cumsum(Y1)), aes(x=1.25, xend=1.75, y=Baseline, yend=Y1))+ 
  geom_segment(data=Bacteroides.ra.mean %>% arrange(by=desc(species)) %>% mutate(Y1=cumsum(Y1)) %>% mutate(Y2=cumsum(Y2)), aes(x=2.25, xend=2.75, y=Y1, yend=Y2))+
  scale_y_continuous(expand=c(0,0))+
   theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(fill = guide_legend(title = 'Bacteroides'))+
  scale_fill_manual(values = c(mypal2,mypal1))+
   labs(y = "Abundance(%)",x=NULL)


```



## Figure 1e


```{r,echo=T}

metadata_meta <- read.csv('input/metadata_meta_107.csv',header=T,row.names = 2)
species <- read.table('input/metaphlan2_merged_species.txt',header = T,sep='\t')
tax <- read.table('input/tax.txt',header = T,sep='\t')

rural.met <- subset(metadata_meta,metadata_meta$region%in%c('rural'))

species.tax <- data.frame(species=species$species)
species.tax <- merge(tax,species.tax,by='species')
species.tax <- species.tax[!duplicated(species.tax$species), ] 
species <- merge(species.tax,species,by='species')

Bacteria <- subset(species,kingdom=='Bacteria')
rownames(Bacteria) <- Bacteria$species

Bacteria.ra <- Bacteria[,c(8:114)]
Bacteria.ra <- as.data.frame(t(Bacteria.ra))
Bacteria.ra <- Bacteria.ra[rownames(rural.met),]



top10.species <- data.frame('mean'=colMeans(Bacteria.ra))
top10.species$species <- rownames(top10.species)
top10.species <- top10.species[order(top10.species$mean,decreasing = T),]
top10.species <- top10.species[c(1:10),]




ggplot(data=Bacteria.ra,aes(x=Prevotella_copri,y=Bacteroides_ovatus))+ geom_point(size=2)+stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=Bacteria.ra, method = "spearman")+
labs(x = "P. copri (%)", y = "B. ovatus (%)")+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,face='italic',colour = 'black'), axis.title.y=element_text(size=14,face='italic',colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))

```


## Figure 1f,1g,1h

```{r,echo=F}

library(reshape2)
library(ggplot2)
library(ggpubr)

BO <- read.csv('input/宏基因组样本Bo绝对定量结果.csv',header = T)

Pc <- read.csv('input/宏基因组样本Pc绝对定量结果-22.9.20.csv',header = T,check.names = F)

Pc.1 <- Pc[Pc$ID%in%BO$ID,]

Pc.Bo <- merge(Pc,BO,by='ID')


met <- read.csv('input/metadata_meta_107.csv')


Pc.Bo <- merge(Pc.Bo,met,by='ID')

Pc.Bo$relocation.years <- car::recode(Pc.Bo.Ct$relocation.years,"'1M'='Baseline';'1Y'='Year1';'2Y'='Year2'")


Pc.Bo$relocation.years <- factor(Pc.Bo.Ct$relocation.years,levels = c('urban','Baseline','Year1','Year2'))

Pc.Bo.1 <- subset(Pc.Bo,Pc.Bo$region=='rural')

 




ggplot(Pc.Bo.1,aes(x=relocation.years,y=Pc,fill=relocation.years))+ #”fill=“设置填充颜色
    geom_boxplot(size=0.4,width=0.3,outlier.fill="white",outlier.color="white")+ #size设置箱线图的边框线和胡须的线宽度，fill设置填充颜色，outlier.fill和outlier.color设置异常点的属性
    geom_jitter(width=0.1,color="black",shape = 20,size=1)+ #设置为向水平方向抖动的散点图，width指定了向水平方向抖动，不改变纵轴的值
    scale_color_manual(values="black")+ #设置散点图的圆圈的颜色为黑色
    theme_cleveland()+ #背景变为白色
    theme(legend.position="none", #不需要图例
          strip.text = element_text(colour="black",size=12,face="italic"),
          strip.background = element_blank(),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="italic",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
  ggtitle('Absolute quantitative of P. copri')+
    ylab("(log10(copies/ng)")+xlab("")+  #设置x轴和y轴的标题

  stat_compare_means(method = 'wilcox',label = 'p.signif',comparisons = list(c('Baseline','Year1'),c('Baseline','Year2')))+
   ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)



ggplot(Pc.Bo.1,aes(x=relocation.years,y=Bo,fill=relocation.years))+ #”fill=“设置填充颜色
    geom_boxplot(size=0.4,width=0.3,outlier.fill="white",outlier.color="white")+ #size设置箱线图的边框线和胡须的线宽度，fill设置填充颜色，outlier.fill和outlier.color设置异常点的属性
    geom_jitter(width=0.1,color="black",shape = 20,size=1)+ #设置为向水平方向抖动的散点图，width指定了向水平方向抖动，不改变纵轴的值
    scale_color_manual(values="black")+ #设置散点图的圆圈的颜色为黑色
    theme_cleveland()+ #背景变为白色
    theme(legend.position="none", #不需要图例
          strip.text = element_text(colour="black",size=12,face="italic"),
          strip.background = element_blank(),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black"), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="italic",hjust = 0.5), #设置总标题的字体属性
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
  ggtitle('Absolute quantitative of B. ovatus')+
    ylab("(log10(copies/ng)")+xlab("")+  #设置x轴和y轴的标题

  stat_compare_means(method = 'wilcox',label = 'p.signif',comparisons = list(c('Baseline','Year1'),c('Baseline','Year2')))+
   ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)
 




 ggplot(data=Pc.Bo,aes(x=Pc.Bo$Pc,y=Pc.Bo$Bo))+ 
   geom_point(size=2)+
   stat_smooth(method="lm",se=T,colour='red')+
  stat_cor(data=Pc.Bo, method = "spearman")+
  ggtitle('Correlation on absolute quantitative data')+
labs(x = "P.copri", y = "B.ovatus")+
  theme_cleveland()+ 
  theme(panel.grid=element_blank()) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black',face = 'italic'), axis.title.y=element_text(size=14,colour = 'black',face = 'italic'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))+
  scale_fill_manual(values = c('red','#0012f8','#b200f8','#04f60b','#bf812d'))
```
