

# Figure 6A
```{r}
mypal1 <- ggsci::pal_lancet( alpha = 1)(9) 
mypal2 <- ggsci::pal_npg( alpha = 0.5)(9)



library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)


ATP.result <- read.csv('ATP assay Results.txt',header=T,sep = '\t')

ATP.result$Group <- factor(ATP.result$Group,levels = unique(ATP.result$Group))




ggplot(ATP.result,aes(x=Group,y=ATP,fill=Group))+ 
    geom_boxplot(size=0.4,width=0.3,outlier.fill="white",outlier.color="white")+ 
    geom_jitter(width=0.15,color="black",shape = 20,size=3)+ 
    scale_fill_manual(values = mypal1)+  
    scale_color_manual(values="black")+ 
    theme_cleveland()+ 
    theme(legend.position="none", 
          axis.text.x=element_text(colour="black",size=14,face = 'italic'), 
          axis.text.y=element_text(size=14,colour="black"), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14), 
          plot.title = element_text(size=16,hjust = 0.5), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  ggtitle('ATP concentration(μM) 
    per gram of bacteria')+
    ylab(NULL)+xlab(NULL)+  
    stat_compare_means(label = "p.signif",comparisons=list(c('P. copri','B. ovatus'),c('P. copri','B. vulgatus'),c('B. vulgatus','B. ovatus')))+
  ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)

ATP.result.1 <- subset(ATP.result,Group%in%c('P. copri','B. ovatus'))



ggplot(ATP.result.1,aes(x=Group,y=ATP,fill=Group))+ 
    geom_boxplot(size=0.4,width=0.3,outlier.fill="white",outlier.shape = NA)+ 
    geom_jitter(width=0.15,color="black",shape = 20,size=3)+ 
    scale_fill_manual(values = mypal1)+  
    scale_color_manual(values="black")+ 
    theme_cleveland()+ 
    theme(legend.position="none", 
          axis.text.x=element_text(colour="black",size=14,face = 'italic'), 
          axis.text.y=element_text(size=14,colour="black"), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14), 
          plot.title = element_text(size=16,hjust = 0.5), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  ggtitle('ATP concentration(μM) 
    per gram of bacteria')+
    ylab(NULL)+xlab(NULL)+  
    stat_compare_means(label = "p.signif",comparisons=list(c('P. copri','B. ovatus')))+
  ggsci::scale_color_npg(alpha = 0.8)+
  ggsci::scale_fill_npg(alpha = 0.8)

```
# Figure 6B

```{r}
PC.MET.result <- read.csv('2022.5.7-crz-ATP.csv',header=F)




colnames(PC.MET.result) <- PC.MET.result[1,]
PC.MET.result <- PC.MET.result[-1,]

PC.MET.result <- melt(PC.MET.result,id.vars = colnames(PC.MET.result[,1:2]))


PC.MET.result <- PC.MET.result[grep('PC',PC.MET.result$variable),]

PC.MET.result$Species <- c('P. copri')


PC.MET.result <- subset(PC.MET.result,PC.MET.result$variable%in%c('PC+0.5mM ATP','PC','RCM'))


library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
PC.MET.result$value <- as.numeric(PC.MET.result$value)

PC.MET.result$Time_h <-factor(PC.MET.result$Time_h,levels= unique(PC.MET.result$Time_h))



PC.p <- compare_means(
  value~variable,
  data=PC.MET.result,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time_h'),
  p.adjust.method = "holm")





library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

PC.MET.result %>%
  mutate(Time_h=as.factor(Time_h)) %>% 
  group_by(variable) %>%
  ggplot(aes(x = Time_h,y =value,
           group=variable,color=variable)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,size=16,colour = 'black',face = 'italic')) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('P. copri')





```

# Figure 6B

```{r}
BO.MET.result <- read.csv('2022.5.7-crz-ATP.csv',header=F)



colnames(BO.MET.result) <- BO.MET.result[1,]
BO.MET.result <- BO.MET.result[-1,]

BO.MET.result <- melt(BO.MET.result,id.vars = colnames(BO.MET.result[,1:2]))


BO.MET.result <- BO.MET.result[grep('BO',BO.MET.result$variable),]

BO.MET.result$Species <- c('B. ovatus')



BO.MET.result <- subset(BO.MET.result,BO.MET.result$variable%in%c('BO+0.5mM ATP','BO','RCM'))


library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)
BO.MET.result$value <- as.numeric(BO.MET.result$value)

BO.MET.result$Time_h <-factor(BO.MET.result$Time_h,levels= unique(BO.MET.result$Time_h))



BO.p <- compare_means(
  value~variable,
  data=BO.MET.result,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time_h'),
  p.adjust.method = "holm")





library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

BO.MET.result %>%
  mutate(Time_h=as.factor(Time_h)) %>% 
  group_by(variable) %>%
  ggplot(aes(x = Time_h,y =value,
           group=variable,color=variable)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,size=16,colour = 'black',face = 'italic')) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('B. ovatus')


```
# Figure 6C-PCA
                     
```{r,echo = TRUE}

library(ggbiplot)
library(ggpubr)


count.new <- read.csv('count.new.csv',header = T,row.names = 1)
met <- read.csv('met.txt',header = T,sep = '\t')
met <- met[-13,]

pca <- prcomp(t(count.new), scale. = TRUE)



df_r<- as.data.frame(pca$rotation *100) 
df_r$feature<- row.names(df_r)



ggbiplot(pca, obs.scale = 1, var.scale = 1,
         groups = met$group, ellipse = TRUE,var.axes = F)+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black') ) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_blank())+
  scale_color_manual(values = mypal1)+
   labs(title = 'Metabolite phenotype',x=paste("PC1(78.9%)"),y=paste("PC2(7.8%)"))
```

# Figure 6D
                     
```{r}

met <- read.csv('met.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('pos_丰度表.csv',header=T,row.names=1)

count.tax <- read.csv('pos_tax.csv',header=T,row.names=1)

count.tax.1 <- count.tax[rownames(count),]

count.tax.1 <- subset(count.tax.1,count.tax.1$score>0.9)

count.tax.1 <- subset(count.tax.1,count.tax.1$Class.I%in%c('Nucleotide And Its metabolomics'))

count.tax.1$Index <- rownames(count.tax.1)
count.nc<- count[rownames(count.tax.1),]

count.nc$Index <- rownames(count.nc)
count.nc <- merge(count.tax.1[,c(1,19)],count.nc,by='Index')
rownames(count.nc) <- count.nc$Compounds
count.nc <- count.nc[,-c(1:2)]
count.nc <- count.nc[order(count.nc$RCM1,decreasing = T),]

count.nc <- as.data.frame(t(count.nc))
count.nc$group <- met$group
count.nc$sample.id <-rownames(count.nc) 

count.nc.long <- melt(count.nc)

count.nc.long$group <- factor(count.nc.long$group,levels = c("RCM","B.ovatus","P.copri"))


count.nc.long <- count.nc.long[order(count.nc.long$value,decreasing = T),]

ggplot(count.nc.long, aes(sample.id, value, fill = variable))+
geom_col(position = 'stack', width = 1) +
  scale_y_continuous(expand=c(0,0))+
  theme_cleveland()+ 
  facet_grid(~group,scales = 'free',space = "free_x")+
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,size=16,colour = 'black')) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_blank(),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_blank())+
    ylab('Integral area')+
  xlab("Sample ID")+
  ggtitle('Nucleotide metabolomics')+
  scale_fill_manual(values = c(mypal1,mypal2))




### 按照空白RCM进行改变倍数比较 
                     

met <- read.csv('met.txt',header = T,row.names = 1,sep='\t')

count <- read.csv('pos_丰度表.csv',header=T,row.names=1)

count.tax <- read.csv('pos_tax.csv',header=T,row.names=1)

count.tax.1 <- count.tax[rownames(count),]

count.tax.1 <- subset(count.tax.1,count.tax.1$score>0.9)

count.tax.1 <- subset(count.tax.1,count.tax.1$Class.I%in%c('Nucleotide And Its metabolomics'))

count.tax.1$Index <- rownames(count.tax.1)
count.nc<- count[rownames(count.tax.1),]

count.nc$Index <- rownames(count.nc)
count.nc <- merge(count.tax.1[,c(1,19)],count.nc,by='Index')
rownames(count.nc) <- count.nc$Compounds
count.nc <- count.nc[,-c(1:2)]
count.nc <- count.nc[order(count.nc$RCM1,decreasing = T),]

RCM <- count.nc$RCM1

nc.foldchage <- (count.nc-RCM)/RCM

nc.foldchage <- as.data.frame(t(nc.foldchage)) 


nc.foldchage$group <- met$group

nc.foldchage.long <- melt(nc.foldchage[-13,])

nc.foldchage.long $variable <- factor(nc.foldchage.long $variable,levels = unique(rownames(count.nc)))


nc.foldchage.long$meta <- car::recode(nc.foldchage.long$value,'0:10000="red";else="blue"')



library(ggbreak)

ggplot(nc.foldchage.long,aes(x= variable,y=value,fill= group))+ #”fill=“设置填充颜色
    geom_boxplot(size=0.4,width=0.8,outlier.shape = NA)+ #size设置箱线图的边框线和胡须的线宽度，fill设置填充颜色，outlier.fill和outlier.color设置异常点的属性
 #   geom_point(width=0.05,aes(color=group),shape = 20,size=2)+ #设置为向水平方向抖动的散点图，width指定了向水平方向抖动，不改变纵轴的值
    scale_fill_manual(values =c(mypal1,mypal2))+  #设置填充的颜色
    scale_color_manual(values=c(mypal1,mypal2))+
#  geom_rect(aes(ymin=-1, ymax=0, xmin=-Inf, xmax=Inf),color='#FFDDEE',alpha = .002)+
  #设置散点图的圆圈的颜色为黑色
    theme_cleveland()+ #背景变为白色
    theme(legend.position="top", 
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black",face = 'italic'), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
          #plot.background = element_rect(aes(fill=nc.foldchage.long$meta)),
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
  ggtitle('Nucleotide metabolomics')+
    ylab("Foldchage to RCM")+xlab("")+  #设置x轴和y轴的标题
   coord_flip()+
  scale_y_break(c(4, 55),ticklabels=c(56,58),scales = 0.3)+
  geom_hline(aes(yintercept=0), colour="black", linetype="dashed")+
  ggpubr::stat_compare_means(method = 'wilcox',label = 'p.signif')
  





nc.foldchage.long %>%
  mutate(variable=as.factor(variable)) %>% 
  group_by(group) %>%
  ggplot(aes(x = variable,y =value,
           fill=group,group=group)) +                          
  stat_summary(fun.y="mean",geom="bar",size=0.5,position = position_dodge()) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.5,position = position_dodge(0.8))+
  theme_cleveland()+ #背景变为白色
    theme(legend.position="top", 
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), #设置x轴刻度标签的字体属性
          axis.text.y=element_text(size=14,colour="black",face = 'italic'), #设置x轴刻度标签的字体属性
          axis.title.y=element_text(size = 14,vjust = 2), #设置y轴的标题的字体属性
          axis.title.x=element_text(size = 14), #设置x轴的标题的字体属性
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
         # plot.background = element_rect(aes(fill=nc.foldchage.long$meta)),
          panel.grid.major = element_blank(), #不显示网格线
          panel.grid.minor = element_blank())+
  ggtitle('Nucleotide metabolomics')+
    ylab("Foldchage to RCM")+xlab("")+  #设置x轴和y轴的标题
   coord_flip()+
  scale_y_break(c(4, 55),ticklabels=c(56,58),scales = 0.3)+
  geom_hline(aes(yintercept=0), colour="black", linetype="dashed")+
  ggpubr::stat_compare_means(method = 'wilcox',label = 'p.signif')+
      scale_fill_manual(values =c(mypal1,mypal2))+  #设置填充的颜色
    scale_color_manual(values=c(mypal1,mypal2))









```


# Figure 6E and Figure S9A

```{r}
BO.MET.result <- read.csv('DEo-crz-Bo.csv',header=T)


mean <- aggregate(BO.MET.result$OD600,list(BO.MET.result$Group,BO.MET.result$Time.h),mean)

library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)






BO.p <- compare_means(
  OD600~Group,
  data=BO.MET.result,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time.h'),
  p.adjust.method = "holm")




library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

BO.MET.result %>%
  mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,color=Group)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=16,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,face = 'italic',colour = 'black',)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
  ggtitle('B. ovatus')+
   labs(y = "OD600",x='Incubation time (h)')


BO.MET.result.1 <- subset(BO.MET.result,BO.MET.result$Group%in%c("RCM","RCM+ DEo","Bo+3mM DEo","Bo+2mM DEo","Bo+1.6mM DEo","Bo+1.2mM DEo","Bo+0.8mM DEo","Bo+0.4mM DEo","Bo"))



BO.MET.result.1 %>%
  mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,color=Group)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=16,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,face = 'italic',colour = 'black',)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
  ggtitle('B. ovatus')+
   labs(y = "OD600",x='Incubation time (h)')






BO.MET.result.2 <- subset(BO.MET.result,BO.MET.result$Group%in%c("Bo+3mM DEo","Bo+2mM DEo","Bo+1.6mM DEo","Bo+1.2mM DEo","Bo+0.8mM DEo","Bo+0.4mM DEo","Bo"))




BO.MET.result.2 %>%
   mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,fill=Group)) +                           
  stat_summary(fun.y="mean",geom="bar",size=0.5,position = position_dodge()) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.5,position = position_dodge(0.9))+
  theme_cleveland()+ 
    theme(legend.position="top", 
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), 
          axis.text.y=element_text(size=14,colour="black",face = 'italic'), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14), 
          plot.title = element_text(size=16,face="bold",hjust = 0.5), 
          #plot.background = element_rect(aes(fill=nc.foldchage.long$meta)),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  theme(legend.title = element_blank())+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('B.ovatus')+
  ggpubr::stat_compare_means(method = 'kruskal',label = 'p.signif')+
      scale_fill_manual(values =c(mypal1,mypal2))+  
    scale_color_manual(values=c(mypal1,mypal2))




BO.MET.result.3 <- subset(BO.MET.result.2,BO.MET.result.2$Time.h>0)

BO.MET.result.3 %>%
   mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,fill=Group)) +                           
  stat_summary(fun.y="mean",geom="bar",size=0.5,position = position_dodge()) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.5,position = position_dodge(0.9))+
  theme_cleveland()+ 
    theme(legend.position="top", 
          legend.text = element_text(colour="black",size=14,face = 'italic'),
          legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14), 
          axis.text.y=element_text(size=14,colour="black",face = 'italic'), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14), 
          plot.title = element_text(size=16,face="bold",hjust = 0.5), 
          #plot.background = element_rect(aes(fill=nc.foldchage.long$meta)),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
  theme(legend.title = element_blank())+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('B.ovatus')+
  ggpubr::stat_compare_means(method = 'kruskal',label = 'p.signif',label.y = 0.35)+
      scale_fill_manual(values =c(mypal1,mypal2))+  
    scale_color_manual(values=c(mypal1,mypal2))
    
    
```

# Figure S9B

```{r}
PC.MET.result <- read.csv('DEo-crz-Pc.csv',header=T)



library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)






PC.p <- compare_means(
  OD600~Group,
  data=PC.MET.result,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time.h'),
  p.adjust.method = "holm")





library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

PC.MET.result %>%
  mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,color=Group)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,size=16,colour = 'black',face = 'italic')) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('P. copri')+ylim(0.04,0.2)



PC.MET.result.1 <- subset(PC.MET.result,PC.MET.result$Group%in%c("RCM","RCM+ DEo","Pc+3mM DEo","Pc+2mM DEo","Pc+1.6mM DEo","Pc+1.2mM DEo","Pc+0.8mM DEo","Pc+0.4mM DEo","Pc"))



PC.MET.result.1 %>%
  mutate(Time_h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time_h,y =OD600,
           group=Group,color=Group)) +                          
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=14,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,size=16,colour = 'black',face = 'italic')) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "OD600",x='Incubation time (h)')+
  ggtitle('P. copri')+ylim(0.04,0.2)


```


# Figure 6F

```{r}
Deo <- read.csv('HPLC.txt',header=T,sep='\t')



library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)






Deo.p <- compare_means(
  DEo~Group,
  data=Deo,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time'),
  p.adjust.method = "holm")





library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)



Deo %>%
   mutate(Time=as.factor(Time)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Group,y =DEo,
           group=Time,fill=Time)) +                           
  stat_summary(fun.y="mean",geom="bar",size=0.5,position = position_dodge()) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.5,position = position_dodge(0.9))+
  theme_cleveland()+ 
    theme(legend.position="right", 
          legend.text = element_text(colour="black",size=14),
          legend.title = element_blank(),
          axis.text.x=element_text(colour="black",size=14,angle = 70,vjust = 1,hjust = 1),
          axis.text.y=element_text(size=14,colour="black"), 
          axis.title.y=element_text(size = 14,vjust = 2), 
          axis.title.x=element_text(size = 14), 
          plot.title = element_text(size=16,face="bold",hjust = 0.5), #设置总标题的字体属性
         # plot.background = element_rect(aes(fill=nc.foldchage.long$meta)),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())+
 theme(legend.text = element_text(size=14,colour = 'black')) +
  theme(legend.title = element_text(size=14,colour = 'black'))+
  guides(fill = guide_legend(title = 'Time (h)'))+
  scale_color_manual(values = c(mypal1,mypal2))+
   labs(y = "DEo concentration(mM)",x='')+
  ggpubr::stat_compare_means(method = 't.test',label = 'p.signif')+
      scale_fill_manual(values =c(mypal1,mypal2))+  
    scale_color_manual(values=c(mypal1,mypal2))



```
#  Figure 6G

```{r}
PC.MET.result <- read.table('Deo-LB.txt',header=T,sep='\t')

PC.MET.result$Group <- factor(PC.MET.result$Group,unique(PC.MET.result$Group))


library(reshape2)
library(ggplot2)
library(ggpubr)
library(patchwork)





PC.p <- compare_means(
  OD600~Group,
  data=PC.MET.result,
  method = "t.test",
  paired = FALSE,
  group.by =c('Time.h'),
  p.adjust.method = "holm")




library(tidyverse)
library(ggsci)
library(patchwork)
library(ggpubr)

PC.MET.result %>%
  mutate(Time.h=as.factor(Time.h)) %>% 
  group_by(Group) %>%
  ggplot(aes(x = Time.h,y =OD600,
           group=Group,color=Group)) +                            
  stat_summary(fun.y="mean",geom="point",size=3) +        
  stat_summary(fun.y="mean",geom="line",size=1) +  
  stat_summary(fun.data = "mean_se",geom = "errorbar",width=0.1)+
  scale_color_nejm()+
  theme_cleveland()+ 
  theme(panel.grid=element_blank(),
        strip.background =element_blank(),
        strip.text =element_text(size=16,colour = 'black',face = 'italic') ) + 
  theme(plot.title = element_text(hjust = 0.5,face = 'italic',colour = 'black',)) + 
  theme(axis.title.x =element_text(size=14,colour = 'black'), axis.title.y=element_text(size=14,colour = 'black'))+ 
  theme(axis.text.x = element_text(size=14,colour = 'black'),axis.text.y = element_text(size=14,colour = 'black')) + 
  theme(legend.text = element_text(size=14,colour = 'black',face = 'italic')) +
  theme(legend.title = element_text(size=14,colour = 'black',face = 'italic'))+
  guides(color = guide_legend(title = ''))+
  scale_color_manual(values = c(mypal1,mypal2))+
  ggtitle('P. copri in nutrient restricted LB medium')+
   labs(y = "OD600",x='Incubation time (h)')


```